// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_host_query_reset
//

// Package mock_host_query_reset is a generated GoMock package.
package mock_host_query_reset

import (
	reflect "reflect"

	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// ResetQueryPool mocks base method.
func (m *MockExtensionDriver) ResetQueryPool(queryPool core1_0.QueryPool, firstQuery, queryCount int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetQueryPool", queryPool, firstQuery, queryCount)
}

// ResetQueryPool indicates an expected call of ResetQueryPool.
func (mr *MockExtensionDriverMockRecorder) ResetQueryPool(queryPool, firstQuery, queryCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetQueryPool", reflect.TypeOf((*MockExtensionDriver)(nil).ResetQueryPool), queryPool, firstQuery, queryCount)
}
