// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_host_query_reset
//

// Package mock_host_query_reset is a generated GoMock package.
package mock_host_query_reset

import (
	reflect "reflect"

	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	gomock "go.uber.org/mock/gomock"
)

// MockExtension is a mock of Extension interface.
type MockExtension struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionMockRecorder
	isgomock struct{}
}

// MockExtensionMockRecorder is the mock recorder for MockExtension.
type MockExtensionMockRecorder struct {
	mock *MockExtension
}

// NewMockExtension creates a new mock instance.
func NewMockExtension(ctrl *gomock.Controller) *MockExtension {
	mock := &MockExtension{ctrl: ctrl}
	mock.recorder = &MockExtensionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtension) EXPECT() *MockExtensionMockRecorder {
	return m.recorder
}

// ResetQueryPool mocks base method.
func (m *MockExtension) ResetQueryPool(queryPool core1_0.QueryPool, firstQuery, queryCount int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetQueryPool", queryPool, firstQuery, queryCount)
}

// ResetQueryPool indicates an expected call of ResetQueryPool.
func (mr *MockExtensionMockRecorder) ResetQueryPool(queryPool, firstQuery, queryCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetQueryPool", reflect.TypeOf((*MockExtension)(nil).ResetQueryPool), queryPool, firstQuery, queryCount)
}
