// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_host_query_reset
//

// Package mock_host_query_reset is a generated GoMock package.
package mock_host_query_reset

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkResetQueryPoolEXT mocks base method.
func (m *MockLoader) VkResetQueryPoolEXT(device loader.VkDevice, queryPool loader.VkQueryPool, firstQuery, queryCount loader.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkResetQueryPoolEXT", device, queryPool, firstQuery, queryCount)
}

// VkResetQueryPoolEXT indicates an expected call of VkResetQueryPoolEXT.
func (mr *MockLoaderMockRecorder) VkResetQueryPoolEXT(device, queryPool, firstQuery, queryCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkResetQueryPoolEXT", reflect.TypeOf((*MockLoader)(nil).VkResetQueryPoolEXT), device, queryPool, firstQuery, queryCount)
}
