// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_get_memory_requirements2
//

// Package mock_get_memory_requirements2 is a generated GoMock package.
package mock_get_memory_requirements2

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_get_memory_requirements2_loader "github.com/vkngwrapper/extensions/v3/khr_get_memory_requirements2/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkGetBufferMemoryRequirements2KHR mocks base method.
func (m *MockLoader) VkGetBufferMemoryRequirements2KHR(device loader.VkDevice, pInfo *khr_get_memory_requirements2_loader.VkBufferMemoryRequirementsInfo2KHR, pMemoryRequirements *khr_get_memory_requirements2_loader.VkMemoryRequirements2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetBufferMemoryRequirements2KHR", device, pInfo, pMemoryRequirements)
}

// VkGetBufferMemoryRequirements2KHR indicates an expected call of VkGetBufferMemoryRequirements2KHR.
func (mr *MockLoaderMockRecorder) VkGetBufferMemoryRequirements2KHR(device, pInfo, pMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetBufferMemoryRequirements2KHR", reflect.TypeOf((*MockLoader)(nil).VkGetBufferMemoryRequirements2KHR), device, pInfo, pMemoryRequirements)
}

// VkGetImageMemoryRequirements2KHR mocks base method.
func (m *MockLoader) VkGetImageMemoryRequirements2KHR(device loader.VkDevice, pInfo *khr_get_memory_requirements2_loader.VkImageMemoryRequirementsInfo2KHR, pMemoryRequirements *khr_get_memory_requirements2_loader.VkMemoryRequirements2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetImageMemoryRequirements2KHR", device, pInfo, pMemoryRequirements)
}

// VkGetImageMemoryRequirements2KHR indicates an expected call of VkGetImageMemoryRequirements2KHR.
func (mr *MockLoaderMockRecorder) VkGetImageMemoryRequirements2KHR(device, pInfo, pMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetImageMemoryRequirements2KHR", reflect.TypeOf((*MockLoader)(nil).VkGetImageMemoryRequirements2KHR), device, pInfo, pMemoryRequirements)
}

// VkGetImageSparseMemoryRequirements2KHR mocks base method.
func (m *MockLoader) VkGetImageSparseMemoryRequirements2KHR(device loader.VkDevice, pInfo *khr_get_memory_requirements2_loader.VkImageSparseMemoryRequirementsInfo2KHR, pSparseMemoryRequirementCount *loader.Uint32, pSparseMemoryRequirements *khr_get_memory_requirements2_loader.VkSparseImageMemoryRequirements2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetImageSparseMemoryRequirements2KHR", device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
}

// VkGetImageSparseMemoryRequirements2KHR indicates an expected call of VkGetImageSparseMemoryRequirements2KHR.
func (mr *MockLoaderMockRecorder) VkGetImageSparseMemoryRequirements2KHR(device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetImageSparseMemoryRequirements2KHR", reflect.TypeOf((*MockLoader)(nil).VkGetImageSparseMemoryRequirements2KHR), device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
}
