// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_sampler_ycbcr_conversion
//

// Package mock_sampler_ycbcr_conversion is a generated GoMock package.
package mock_sampler_ycbcr_conversion

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_sampler_ycbcr_conversion_loader "github.com/vkngwrapper/extensions/v3/khr_sampler_ycbcr_conversion/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkCreateSamplerYcbcrConversionKHR mocks base method.
func (m *MockLoader) VkCreateSamplerYcbcrConversionKHR(device loader.VkDevice, pCreateInfo *khr_sampler_ycbcr_conversion_loader.VkSamplerYcbcrConversionCreateInfoKHR, pAllocator *loader.VkAllocationCallbacks, pYcbcrConversion *khr_sampler_ycbcr_conversion_loader.VkSamplerYcbcrConversionKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCreateSamplerYcbcrConversionKHR", device, pCreateInfo, pAllocator, pYcbcrConversion)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCreateSamplerYcbcrConversionKHR indicates an expected call of VkCreateSamplerYcbcrConversionKHR.
func (mr *MockLoaderMockRecorder) VkCreateSamplerYcbcrConversionKHR(device, pCreateInfo, pAllocator, pYcbcrConversion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCreateSamplerYcbcrConversionKHR", reflect.TypeOf((*MockLoader)(nil).VkCreateSamplerYcbcrConversionKHR), device, pCreateInfo, pAllocator, pYcbcrConversion)
}

// VkDestroySamplerYcbcrConversionKHR mocks base method.
func (m *MockLoader) VkDestroySamplerYcbcrConversionKHR(device loader.VkDevice, ycbcrConversion khr_sampler_ycbcr_conversion_loader.VkSamplerYcbcrConversionKHR, pAllocator *loader.VkAllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkDestroySamplerYcbcrConversionKHR", device, ycbcrConversion, pAllocator)
}

// VkDestroySamplerYcbcrConversionKHR indicates an expected call of VkDestroySamplerYcbcrConversionKHR.
func (mr *MockLoaderMockRecorder) VkDestroySamplerYcbcrConversionKHR(device, ycbcrConversion, pAllocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkDestroySamplerYcbcrConversionKHR", reflect.TypeOf((*MockLoader)(nil).VkDestroySamplerYcbcrConversionKHR), device, ycbcrConversion, pAllocator)
}
