// Code generated by MockGen. DO NOT EDIT.
// Source: shim.go
//
// Generated by this command:
//
//	mockgen -source shim.go -destination ../mocks/shim.go -package mock_sampler_ycbcr_conversion
//

// Package mock_sampler_ycbcr_conversion is a generated GoMock package.
package mock_sampler_ycbcr_conversion

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	core1_1 "github.com/vkngwrapper/core/v3/core1_1"
	driver "github.com/vkngwrapper/core/v3/driver"
	gomock "go.uber.org/mock/gomock"
)

// MockShim is a mock of Shim interface.
type MockShim struct {
	ctrl     *gomock.Controller
	recorder *MockShimMockRecorder
	isgomock struct{}
}

// MockShimMockRecorder is the mock recorder for MockShim.
type MockShimMockRecorder struct {
	mock *MockShim
}

// NewMockShim creates a new mock instance.
func NewMockShim(ctrl *gomock.Controller) *MockShim {
	mock := &MockShim{ctrl: ctrl}
	mock.recorder = &MockShimMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShim) EXPECT() *MockShimMockRecorder {
	return m.recorder
}

// CreateSamplerYcbcrConversion mocks base method.
func (m *MockShim) CreateSamplerYcbcrConversion(o core1_1.SamplerYcbcrConversionCreateInfo, allocator *driver.AllocationCallbacks) (core1_1.SamplerYcbcrConversion, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSamplerYcbcrConversion", o, allocator)
	ret0, _ := ret[0].(core1_1.SamplerYcbcrConversion)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSamplerYcbcrConversion indicates an expected call of CreateSamplerYcbcrConversion.
func (mr *MockShimMockRecorder) CreateSamplerYcbcrConversion(o, allocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSamplerYcbcrConversion", reflect.TypeOf((*MockShim)(nil).CreateSamplerYcbcrConversion), o, allocator)
}
