// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_copy_commands2
//

// Package mock_copy_commands2 is a generated GoMock package.
package mock_copy_commands2

import (
	reflect "reflect"

	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_copy_commands2 "github.com/vkngwrapper/extensions/v3/khr_copy_commands2"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// CmdBlitImage2 mocks base method.
func (m *MockExtensionDriver) CmdBlitImage2(commandBuffer core1_0.CommandBuffer, blitImageInfo khr_copy_commands2.BlitImageInfo2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdBlitImage2", commandBuffer, blitImageInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdBlitImage2 indicates an expected call of CmdBlitImage2.
func (mr *MockExtensionDriverMockRecorder) CmdBlitImage2(commandBuffer, blitImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdBlitImage2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdBlitImage2), commandBuffer, blitImageInfo)
}

// CmdCopyBuffer2 mocks base method.
func (m *MockExtensionDriver) CmdCopyBuffer2(commandBuffer core1_0.CommandBuffer, copyBufferInfo khr_copy_commands2.CopyBufferInfo2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdCopyBuffer2", commandBuffer, copyBufferInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdCopyBuffer2 indicates an expected call of CmdCopyBuffer2.
func (mr *MockExtensionDriverMockRecorder) CmdCopyBuffer2(commandBuffer, copyBufferInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdCopyBuffer2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdCopyBuffer2), commandBuffer, copyBufferInfo)
}

// CmdCopyBufferToImage2 mocks base method.
func (m *MockExtensionDriver) CmdCopyBufferToImage2(commandBuffer core1_0.CommandBuffer, copyBufferToImageInfo khr_copy_commands2.CopyBufferToImageInfo2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdCopyBufferToImage2", commandBuffer, copyBufferToImageInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdCopyBufferToImage2 indicates an expected call of CmdCopyBufferToImage2.
func (mr *MockExtensionDriverMockRecorder) CmdCopyBufferToImage2(commandBuffer, copyBufferToImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdCopyBufferToImage2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdCopyBufferToImage2), commandBuffer, copyBufferToImageInfo)
}

// CmdCopyImage2 mocks base method.
func (m *MockExtensionDriver) CmdCopyImage2(commandBuffer core1_0.CommandBuffer, copyImageInfo khr_copy_commands2.CopyImageInfo2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdCopyImage2", commandBuffer, copyImageInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdCopyImage2 indicates an expected call of CmdCopyImage2.
func (mr *MockExtensionDriverMockRecorder) CmdCopyImage2(commandBuffer, copyImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdCopyImage2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdCopyImage2), commandBuffer, copyImageInfo)
}

// CmdCopyImageToBuffer2 mocks base method.
func (m *MockExtensionDriver) CmdCopyImageToBuffer2(commandBuffer core1_0.CommandBuffer, copyImageToBufferInfo khr_copy_commands2.CopyImageToBufferInfo2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdCopyImageToBuffer2", commandBuffer, copyImageToBufferInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdCopyImageToBuffer2 indicates an expected call of CmdCopyImageToBuffer2.
func (mr *MockExtensionDriverMockRecorder) CmdCopyImageToBuffer2(commandBuffer, copyImageToBufferInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdCopyImageToBuffer2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdCopyImageToBuffer2), commandBuffer, copyImageToBufferInfo)
}

// CmdResolveImage2 mocks base method.
func (m *MockExtensionDriver) CmdResolveImage2(commandBuffer core1_0.CommandBuffer, resolveImageInfo khr_copy_commands2.ResolveImageInfo2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdResolveImage2", commandBuffer, resolveImageInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdResolveImage2 indicates an expected call of CmdResolveImage2.
func (mr *MockExtensionDriverMockRecorder) CmdResolveImage2(commandBuffer, resolveImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdResolveImage2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdResolveImage2), commandBuffer, resolveImageInfo)
}
