// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_copy_commands2
//

// Package mock_copy_commands2 is a generated GoMock package.
package mock_copy_commands2

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_copy_commands2_loader "github.com/vkngwrapper/extensions/v3/khr_copy_commands2/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkCmdBlitImage2KHR mocks base method.
func (m *MockLoader) VkCmdBlitImage2KHR(commandBuffer loader.VkCommandBuffer, pBlitImageInfo *khr_copy_commands2_loader.VkBlitImageInfo2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdBlitImage2KHR", commandBuffer, pBlitImageInfo)
}

// VkCmdBlitImage2KHR indicates an expected call of VkCmdBlitImage2KHR.
func (mr *MockLoaderMockRecorder) VkCmdBlitImage2KHR(commandBuffer, pBlitImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdBlitImage2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdBlitImage2KHR), commandBuffer, pBlitImageInfo)
}

// VkCmdCopyBuffer2KHR mocks base method.
func (m *MockLoader) VkCmdCopyBuffer2KHR(commandBuffer loader.VkCommandBuffer, pCopyBufferInfo *khr_copy_commands2_loader.VkCopyBufferInfo2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdCopyBuffer2KHR", commandBuffer, pCopyBufferInfo)
}

// VkCmdCopyBuffer2KHR indicates an expected call of VkCmdCopyBuffer2KHR.
func (mr *MockLoaderMockRecorder) VkCmdCopyBuffer2KHR(commandBuffer, pCopyBufferInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdCopyBuffer2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdCopyBuffer2KHR), commandBuffer, pCopyBufferInfo)
}

// VkCmdCopyBufferToImage2KHR mocks base method.
func (m *MockLoader) VkCmdCopyBufferToImage2KHR(commandBuffer loader.VkCommandBuffer, pCopyBufferToImageInfo *khr_copy_commands2_loader.VkCopyBufferToImageInfo2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdCopyBufferToImage2KHR", commandBuffer, pCopyBufferToImageInfo)
}

// VkCmdCopyBufferToImage2KHR indicates an expected call of VkCmdCopyBufferToImage2KHR.
func (mr *MockLoaderMockRecorder) VkCmdCopyBufferToImage2KHR(commandBuffer, pCopyBufferToImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdCopyBufferToImage2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdCopyBufferToImage2KHR), commandBuffer, pCopyBufferToImageInfo)
}

// VkCmdCopyImage2KHR mocks base method.
func (m *MockLoader) VkCmdCopyImage2KHR(commandBuffer loader.VkCommandBuffer, pCopyImageInfo *khr_copy_commands2_loader.VkCopyImageInfo2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdCopyImage2KHR", commandBuffer, pCopyImageInfo)
}

// VkCmdCopyImage2KHR indicates an expected call of VkCmdCopyImage2KHR.
func (mr *MockLoaderMockRecorder) VkCmdCopyImage2KHR(commandBuffer, pCopyImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdCopyImage2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdCopyImage2KHR), commandBuffer, pCopyImageInfo)
}

// VkCmdCopyImageToBuffer2KHR mocks base method.
func (m *MockLoader) VkCmdCopyImageToBuffer2KHR(commandBuffer loader.VkCommandBuffer, pCopyImageToBufferInfo *khr_copy_commands2_loader.VkCopyImageToBufferInfo2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdCopyImageToBuffer2KHR", commandBuffer, pCopyImageToBufferInfo)
}

// VkCmdCopyImageToBuffer2KHR indicates an expected call of VkCmdCopyImageToBuffer2KHR.
func (mr *MockLoaderMockRecorder) VkCmdCopyImageToBuffer2KHR(commandBuffer, pCopyImageToBufferInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdCopyImageToBuffer2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdCopyImageToBuffer2KHR), commandBuffer, pCopyImageToBufferInfo)
}

// VkCmdResolveImage2KHR mocks base method.
func (m *MockLoader) VkCmdResolveImage2KHR(commandBuffer loader.VkCommandBuffer, pResolveImageInfo *khr_copy_commands2_loader.VkResolveImageInfo2KHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdResolveImage2KHR", commandBuffer, pResolveImageInfo)
}

// VkCmdResolveImage2KHR indicates an expected call of VkCmdResolveImage2KHR.
func (mr *MockLoaderMockRecorder) VkCmdResolveImage2KHR(commandBuffer, pResolveImageInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdResolveImage2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdResolveImage2KHR), commandBuffer, pResolveImageInfo)
}
