// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_device_group
//

// Package mock_device_group is a generated GoMock package.
package mock_device_group

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_device_group "github.com/vkngwrapper/extensions/v3/khr_device_group"
	khr_surface "github.com/vkngwrapper/extensions/v3/khr_surface"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// CmdDispatchBase mocks base method.
func (m *MockExtensionDriver) CmdDispatchBase(commandBuffer core1_0.CommandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdDispatchBase", commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ)
}

// CmdDispatchBase indicates an expected call of CmdDispatchBase.
func (mr *MockExtensionDriverMockRecorder) CmdDispatchBase(commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdDispatchBase", reflect.TypeOf((*MockExtensionDriver)(nil).CmdDispatchBase), commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ)
}

// CmdSetDeviceMask mocks base method.
func (m *MockExtensionDriver) CmdSetDeviceMask(commandBuffer core1_0.CommandBuffer, deviceMask uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdSetDeviceMask", commandBuffer, deviceMask)
}

// CmdSetDeviceMask indicates an expected call of CmdSetDeviceMask.
func (mr *MockExtensionDriverMockRecorder) CmdSetDeviceMask(commandBuffer, deviceMask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdSetDeviceMask", reflect.TypeOf((*MockExtensionDriver)(nil).CmdSetDeviceMask), commandBuffer, deviceMask)
}

// GetDeviceGroupPeerMemoryFeatures mocks base method.
func (m *MockExtensionDriver) GetDeviceGroupPeerMemoryFeatures(heapIndex, localDeviceIndex, remoteDeviceIndex int) khr_device_group.PeerMemoryFeatureFlags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceGroupPeerMemoryFeatures", heapIndex, localDeviceIndex, remoteDeviceIndex)
	ret0, _ := ret[0].(khr_device_group.PeerMemoryFeatureFlags)
	return ret0
}

// GetDeviceGroupPeerMemoryFeatures indicates an expected call of GetDeviceGroupPeerMemoryFeatures.
func (mr *MockExtensionDriverMockRecorder) GetDeviceGroupPeerMemoryFeatures(heapIndex, localDeviceIndex, remoteDeviceIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceGroupPeerMemoryFeatures", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeviceGroupPeerMemoryFeatures), heapIndex, localDeviceIndex, remoteDeviceIndex)
}

// WithKHRSurface mocks base method.
func (m *MockExtensionDriver) WithKHRSurface() khr_device_group.ExtensionDriverWithKHRSurface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithKHRSurface")
	ret0, _ := ret[0].(khr_device_group.ExtensionDriverWithKHRSurface)
	return ret0
}

// WithKHRSurface indicates an expected call of WithKHRSurface.
func (mr *MockExtensionDriverMockRecorder) WithKHRSurface() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithKHRSurface", reflect.TypeOf((*MockExtensionDriver)(nil).WithKHRSurface))
}

// WithKHRSwapchain mocks base method.
func (m *MockExtensionDriver) WithKHRSwapchain() khr_device_group.ExtensionDriverWithKHRSwapchain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithKHRSwapchain")
	ret0, _ := ret[0].(khr_device_group.ExtensionDriverWithKHRSwapchain)
	return ret0
}

// WithKHRSwapchain indicates an expected call of WithKHRSwapchain.
func (mr *MockExtensionDriverMockRecorder) WithKHRSwapchain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithKHRSwapchain", reflect.TypeOf((*MockExtensionDriver)(nil).WithKHRSwapchain))
}

// MockExtensionDriverWithKHRSurface is a mock of ExtensionDriverWithKHRSurface interface.
type MockExtensionDriverWithKHRSurface struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverWithKHRSurfaceMockRecorder
	isgomock struct{}
}

// MockExtensionDriverWithKHRSurfaceMockRecorder is the mock recorder for MockExtensionDriverWithKHRSurface.
type MockExtensionDriverWithKHRSurfaceMockRecorder struct {
	mock *MockExtensionDriverWithKHRSurface
}

// NewMockExtensionDriverWithKHRSurface creates a new mock instance.
func NewMockExtensionDriverWithKHRSurface(ctrl *gomock.Controller) *MockExtensionDriverWithKHRSurface {
	mock := &MockExtensionDriverWithKHRSurface{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverWithKHRSurfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriverWithKHRSurface) EXPECT() *MockExtensionDriverWithKHRSurfaceMockRecorder {
	return m.recorder
}

// GetDeviceGroupPresentCapabilities mocks base method.
func (m *MockExtensionDriverWithKHRSurface) GetDeviceGroupPresentCapabilities(outData *khr_device_group.DeviceGroupPresentCapabilities) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceGroupPresentCapabilities", outData)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceGroupPresentCapabilities indicates an expected call of GetDeviceGroupPresentCapabilities.
func (mr *MockExtensionDriverWithKHRSurfaceMockRecorder) GetDeviceGroupPresentCapabilities(outData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceGroupPresentCapabilities", reflect.TypeOf((*MockExtensionDriverWithKHRSurface)(nil).GetDeviceGroupPresentCapabilities), outData)
}

// GetDeviceGroupSurfacePresentModes mocks base method.
func (m *MockExtensionDriverWithKHRSurface) GetDeviceGroupSurfacePresentModes(surface khr_surface.Surface) (khr_device_group.DeviceGroupPresentModeFlags, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceGroupSurfacePresentModes", surface)
	ret0, _ := ret[0].(khr_device_group.DeviceGroupPresentModeFlags)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceGroupSurfacePresentModes indicates an expected call of GetDeviceGroupSurfacePresentModes.
func (mr *MockExtensionDriverWithKHRSurfaceMockRecorder) GetDeviceGroupSurfacePresentModes(surface any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceGroupSurfacePresentModes", reflect.TypeOf((*MockExtensionDriverWithKHRSurface)(nil).GetDeviceGroupSurfacePresentModes), surface)
}

// GetPhysicalDevicePresentRectangles mocks base method.
func (m *MockExtensionDriverWithKHRSurface) GetPhysicalDevicePresentRectangles(physicalDevice core1_0.PhysicalDevice, surface khr_surface.Surface) ([]core1_0.Rect2D, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDevicePresentRectangles", physicalDevice, surface)
	ret0, _ := ret[0].([]core1_0.Rect2D)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPhysicalDevicePresentRectangles indicates an expected call of GetPhysicalDevicePresentRectangles.
func (mr *MockExtensionDriverWithKHRSurfaceMockRecorder) GetPhysicalDevicePresentRectangles(physicalDevice, surface any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDevicePresentRectangles", reflect.TypeOf((*MockExtensionDriverWithKHRSurface)(nil).GetPhysicalDevicePresentRectangles), physicalDevice, surface)
}

// MockExtensionDriverWithKHRSwapchain is a mock of ExtensionDriverWithKHRSwapchain interface.
type MockExtensionDriverWithKHRSwapchain struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverWithKHRSwapchainMockRecorder
	isgomock struct{}
}

// MockExtensionDriverWithKHRSwapchainMockRecorder is the mock recorder for MockExtensionDriverWithKHRSwapchain.
type MockExtensionDriverWithKHRSwapchainMockRecorder struct {
	mock *MockExtensionDriverWithKHRSwapchain
}

// NewMockExtensionDriverWithKHRSwapchain creates a new mock instance.
func NewMockExtensionDriverWithKHRSwapchain(ctrl *gomock.Controller) *MockExtensionDriverWithKHRSwapchain {
	mock := &MockExtensionDriverWithKHRSwapchain{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverWithKHRSwapchainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriverWithKHRSwapchain) EXPECT() *MockExtensionDriverWithKHRSwapchainMockRecorder {
	return m.recorder
}

// AcquireNextImage2 mocks base method.
func (m *MockExtensionDriverWithKHRSwapchain) AcquireNextImage2(o khr_device_group.AcquireNextImageInfo) (int, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireNextImage2", o)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcquireNextImage2 indicates an expected call of AcquireNextImage2.
func (mr *MockExtensionDriverWithKHRSwapchainMockRecorder) AcquireNextImage2(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireNextImage2", reflect.TypeOf((*MockExtensionDriverWithKHRSwapchain)(nil).AcquireNextImage2), o)
}
