// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_device_group
//

// Package mock_device_group is a generated GoMock package.
package mock_device_group

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_device_group_loader "github.com/vkngwrapper/extensions/v3/khr_device_group/loader"
	khr_surface_loader "github.com/vkngwrapper/extensions/v3/khr_surface/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkAcquireNextImage2KHR mocks base method.
func (m *MockLoader) VkAcquireNextImage2KHR(device loader.VkDevice, pAcquireInfo *khr_device_group_loader.VkAcquireNextImageInfoKHR, pImageIndex *loader.Uint32) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkAcquireNextImage2KHR", device, pAcquireInfo, pImageIndex)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkAcquireNextImage2KHR indicates an expected call of VkAcquireNextImage2KHR.
func (mr *MockLoaderMockRecorder) VkAcquireNextImage2KHR(device, pAcquireInfo, pImageIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkAcquireNextImage2KHR", reflect.TypeOf((*MockLoader)(nil).VkAcquireNextImage2KHR), device, pAcquireInfo, pImageIndex)
}

// VkCmdDispatchBaseKHR mocks base method.
func (m *MockLoader) VkCmdDispatchBaseKHR(commandBuffer loader.VkCommandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ loader.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdDispatchBaseKHR", commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ)
}

// VkCmdDispatchBaseKHR indicates an expected call of VkCmdDispatchBaseKHR.
func (mr *MockLoaderMockRecorder) VkCmdDispatchBaseKHR(commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdDispatchBaseKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdDispatchBaseKHR), commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ)
}

// VkCmdSetDeviceMaskKHR mocks base method.
func (m *MockLoader) VkCmdSetDeviceMaskKHR(commandBuffer loader.VkCommandBuffer, deviceMask loader.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdSetDeviceMaskKHR", commandBuffer, deviceMask)
}

// VkCmdSetDeviceMaskKHR indicates an expected call of VkCmdSetDeviceMaskKHR.
func (mr *MockLoaderMockRecorder) VkCmdSetDeviceMaskKHR(commandBuffer, deviceMask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdSetDeviceMaskKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdSetDeviceMaskKHR), commandBuffer, deviceMask)
}

// VkGetDeviceGroupPeerMemoryFeaturesKHR mocks base method.
func (m *MockLoader) VkGetDeviceGroupPeerMemoryFeaturesKHR(device loader.VkDevice, heapIndex, localDeviceIndex, remoteDeviceIndex loader.Uint32, pPeerMemoryFeatures *khr_device_group_loader.VkPeerMemoryFeatureFlagsKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceGroupPeerMemoryFeaturesKHR", device, heapIndex, localDeviceIndex, remoteDeviceIndex, pPeerMemoryFeatures)
}

// VkGetDeviceGroupPeerMemoryFeaturesKHR indicates an expected call of VkGetDeviceGroupPeerMemoryFeaturesKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceGroupPeerMemoryFeaturesKHR(device, heapIndex, localDeviceIndex, remoteDeviceIndex, pPeerMemoryFeatures any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceGroupPeerMemoryFeaturesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceGroupPeerMemoryFeaturesKHR), device, heapIndex, localDeviceIndex, remoteDeviceIndex, pPeerMemoryFeatures)
}

// VkGetDeviceGroupPresentCapabilitiesKHR mocks base method.
func (m *MockLoader) VkGetDeviceGroupPresentCapabilitiesKHR(device loader.VkDevice, pDeviceGroupPresentCapabilities *khr_device_group_loader.VkDeviceGroupPresentCapabilitiesKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeviceGroupPresentCapabilitiesKHR", device, pDeviceGroupPresentCapabilities)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetDeviceGroupPresentCapabilitiesKHR indicates an expected call of VkGetDeviceGroupPresentCapabilitiesKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceGroupPresentCapabilitiesKHR(device, pDeviceGroupPresentCapabilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceGroupPresentCapabilitiesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceGroupPresentCapabilitiesKHR), device, pDeviceGroupPresentCapabilities)
}

// VkGetDeviceGroupSurfacePresentModesKHR mocks base method.
func (m *MockLoader) VkGetDeviceGroupSurfacePresentModesKHR(device loader.VkDevice, surface khr_surface_loader.VkSurfaceKHR, pModes *khr_device_group_loader.VkDeviceGroupPresentModeFlagsKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeviceGroupSurfacePresentModesKHR", device, surface, pModes)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetDeviceGroupSurfacePresentModesKHR indicates an expected call of VkGetDeviceGroupSurfacePresentModesKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceGroupSurfacePresentModesKHR(device, surface, pModes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceGroupSurfacePresentModesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceGroupSurfacePresentModesKHR), device, surface, pModes)
}

// VkGetPhysicalDevicePresentRectanglesKHR mocks base method.
func (m *MockLoader) VkGetPhysicalDevicePresentRectanglesKHR(physicalDevice loader.VkPhysicalDevice, surface khr_surface_loader.VkSurfaceKHR, pRectCount *loader.Uint32, pRects *loader.VkRect2D) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetPhysicalDevicePresentRectanglesKHR", physicalDevice, surface, pRectCount, pRects)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetPhysicalDevicePresentRectanglesKHR indicates an expected call of VkGetPhysicalDevicePresentRectanglesKHR.
func (mr *MockLoaderMockRecorder) VkGetPhysicalDevicePresentRectanglesKHR(physicalDevice, surface, pRectCount, pRects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetPhysicalDevicePresentRectanglesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetPhysicalDevicePresentRectanglesKHR), physicalDevice, surface, pRectCount, pRects)
}
