// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go

// Package mock_external_fence_capabilities is a generated GoMock package.
package mock_external_fence_capabilities

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	driver "github.com/vkngwrapper/core/v2/driver"
	khr_external_fence_capabilities_driver "github.com/vkngwrapper/extensions/v2/khr_external_fence_capabilities/driver"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// VkGetPhysicalDeviceExternalFencePropertiesKHR mocks base method.
func (m *MockDriver) VkGetPhysicalDeviceExternalFencePropertiesKHR(physicalDevice driver.VkPhysicalDevice, pExternalFenceInfo *khr_external_fence_capabilities_driver.VkPhysicalDeviceExternalFenceInfoKHR, pExternalFenceProperties *khr_external_fence_capabilities_driver.VkExternalFencePropertiesKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetPhysicalDeviceExternalFencePropertiesKHR", physicalDevice, pExternalFenceInfo, pExternalFenceProperties)
}

// VkGetPhysicalDeviceExternalFencePropertiesKHR indicates an expected call of VkGetPhysicalDeviceExternalFencePropertiesKHR.
func (mr *MockDriverMockRecorder) VkGetPhysicalDeviceExternalFencePropertiesKHR(physicalDevice, pExternalFenceInfo, pExternalFenceProperties interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetPhysicalDeviceExternalFencePropertiesKHR", reflect.TypeOf((*MockDriver)(nil).VkGetPhysicalDeviceExternalFencePropertiesKHR), physicalDevice, pExternalFenceInfo, pExternalFenceProperties)
}
