// Code generated by MockGen. DO NOT EDIT.
// Source: shim.go

// Package mock_external_fence_capabilities is a generated GoMock package.
package mock_external_fence_capabilities

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core1_1 "github.com/vkngwrapper/core/v2/core1_1"
)

// MockShim is a mock of Shim interface.
type MockShim struct {
	ctrl     *gomock.Controller
	recorder *MockShimMockRecorder
}

// MockShimMockRecorder is the mock recorder for MockShim.
type MockShimMockRecorder struct {
	mock *MockShim
}

// NewMockShim creates a new mock instance.
func NewMockShim(ctrl *gomock.Controller) *MockShim {
	mock := &MockShim{ctrl: ctrl}
	mock.recorder = &MockShimMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShim) EXPECT() *MockShimMockRecorder {
	return m.recorder
}

// ExternalFenceProperties mocks base method.
func (m *MockShim) ExternalFenceProperties(o core1_1.PhysicalDeviceExternalFenceInfo, outData *core1_1.ExternalFenceProperties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalFenceProperties", o, outData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExternalFenceProperties indicates an expected call of ExternalFenceProperties.
func (mr *MockShimMockRecorder) ExternalFenceProperties(o, outData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalFenceProperties", reflect.TypeOf((*MockShim)(nil).ExternalFenceProperties), o, outData)
}
