package khr_maintenance2_driver

/*
#include <stdlib.h>
#include "../../vulkan/vulkan.h"
*/
import "C"
import _ "github.com/vkngwrapper/extensions/v2/vulkan"

type VkInputAttachmentAspectReferenceKHR C.VkInputAttachmentAspectReferenceKHR
type VkImageViewUsageCreateInfoKHR C.VkImageViewUsageCreateInfoKHR
type VkPhysicalDevicePointClippingPropertiesKHR C.VkPhysicalDevicePointClippingPropertiesKHR
type VkPipelineTessellationDomainOriginStateCreateInfoKHR C.VkPipelineTessellationDomainOriginStateCreateInfoKHR
type VkRenderPassInputAttachmentAspectCreateInfoKHR C.VkRenderPassInputAttachmentAspectCreateInfoKHR
type VkPointClippingBehaviorKHR C.VkPointClippingBehaviorKHR
type VkTessellationDomainOriginKHR C.VkTessellationDomainOriginKHR
