// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_maintenance4
//

// Package mock_maintenance4 is a generated GoMock package.
package mock_maintenance4

import (
	reflect "reflect"

	core1_1 "github.com/vkngwrapper/core/v3/core1_1"
	khr_maintenance4 "github.com/vkngwrapper/extensions/v3/khr_maintenance4"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// GetDeviceBufferMemoryRequirements mocks base method.
func (m *MockExtensionDriver) GetDeviceBufferMemoryRequirements(options khr_maintenance4.DeviceBufferMemoryRequirements, outData *core1_1.MemoryRequirements2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceBufferMemoryRequirements", options, outData)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetDeviceBufferMemoryRequirements indicates an expected call of GetDeviceBufferMemoryRequirements.
func (mr *MockExtensionDriverMockRecorder) GetDeviceBufferMemoryRequirements(options, outData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceBufferMemoryRequirements", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeviceBufferMemoryRequirements), options, outData)
}

// GetDeviceImageMemoryRequirements mocks base method.
func (m *MockExtensionDriver) GetDeviceImageMemoryRequirements(options khr_maintenance4.DeviceImageMemoryRequirements, outData *core1_1.MemoryRequirements2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceImageMemoryRequirements", options, outData)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetDeviceImageMemoryRequirements indicates an expected call of GetDeviceImageMemoryRequirements.
func (mr *MockExtensionDriverMockRecorder) GetDeviceImageMemoryRequirements(options, outData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceImageMemoryRequirements", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeviceImageMemoryRequirements), options, outData)
}

// GetDeviceImageSparseMemoryRequirements mocks base method.
func (m *MockExtensionDriver) GetDeviceImageSparseMemoryRequirements(options khr_maintenance4.DeviceImageMemoryRequirements, outDataFactory func() *core1_1.SparseImageMemoryRequirements2) ([]*core1_1.SparseImageMemoryRequirements2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceImageSparseMemoryRequirements", options, outDataFactory)
	ret0, _ := ret[0].([]*core1_1.SparseImageMemoryRequirements2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceImageSparseMemoryRequirements indicates an expected call of GetDeviceImageSparseMemoryRequirements.
func (mr *MockExtensionDriverMockRecorder) GetDeviceImageSparseMemoryRequirements(options, outDataFactory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceImageSparseMemoryRequirements", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeviceImageSparseMemoryRequirements), options, outDataFactory)
}
