// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_maintenance4
//

// Package mock_maintenance4 is a generated GoMock package.
package mock_maintenance4

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_maintenance4_loader "github.com/vkngwrapper/extensions/v3/khr_maintenance4/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkGetDeviceBufferMemoryRequirementsKHR mocks base method.
func (m *MockLoader) VkGetDeviceBufferMemoryRequirementsKHR(device loader.VkDevice, pInfo *khr_maintenance4_loader.VkDeviceBufferMemoryRequirementsKHR, pMemoryRequirements *loader.VkMemoryRequirements2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceBufferMemoryRequirementsKHR", device, pInfo, pMemoryRequirements)
}

// VkGetDeviceBufferMemoryRequirementsKHR indicates an expected call of VkGetDeviceBufferMemoryRequirementsKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceBufferMemoryRequirementsKHR(device, pInfo, pMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceBufferMemoryRequirementsKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceBufferMemoryRequirementsKHR), device, pInfo, pMemoryRequirements)
}

// VkGetDeviceImageMemoryRequirementsKHR mocks base method.
func (m *MockLoader) VkGetDeviceImageMemoryRequirementsKHR(device loader.VkDevice, pInfo *khr_maintenance4_loader.VkDeviceImageMemoryRequirementsKHR, pMemoryRequirements *loader.VkMemoryRequirements2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceImageMemoryRequirementsKHR", device, pInfo, pMemoryRequirements)
}

// VkGetDeviceImageMemoryRequirementsKHR indicates an expected call of VkGetDeviceImageMemoryRequirementsKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceImageMemoryRequirementsKHR(device, pInfo, pMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceImageMemoryRequirementsKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceImageMemoryRequirementsKHR), device, pInfo, pMemoryRequirements)
}

// VkGetDeviceImageSparseMemoryRequirementsKHR mocks base method.
func (m *MockLoader) VkGetDeviceImageSparseMemoryRequirementsKHR(device loader.VkDevice, pInfo *khr_maintenance4_loader.VkDeviceImageMemoryRequirementsKHR, pSparseMemoryRequirementCount *loader.Uint32, pSparseMemoryRequirements *loader.VkSparseImageMemoryRequirements2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceImageSparseMemoryRequirementsKHR", device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
}

// VkGetDeviceImageSparseMemoryRequirementsKHR indicates an expected call of VkGetDeviceImageSparseMemoryRequirementsKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceImageSparseMemoryRequirementsKHR(device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceImageSparseMemoryRequirementsKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceImageSparseMemoryRequirementsKHR), device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
}
