// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_maintenance1
//

// Package mock_maintenance1 is a generated GoMock package.
package mock_maintenance1

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_maintenance1_loader "github.com/vkngwrapper/extensions/v3/khr_maintenance1/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkTrimCommandPoolKHR mocks base method.
func (m *MockLoader) VkTrimCommandPoolKHR(device loader.VkDevice, commandPool loader.VkCommandPool, flags khr_maintenance1_loader.VkCommandPoolTrimFlagsKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkTrimCommandPoolKHR", device, commandPool, flags)
}

// VkTrimCommandPoolKHR indicates an expected call of VkTrimCommandPoolKHR.
func (mr *MockLoaderMockRecorder) VkTrimCommandPoolKHR(device, commandPool, flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkTrimCommandPoolKHR", reflect.TypeOf((*MockLoader)(nil).VkTrimCommandPoolKHR), device, commandPool, flags)
}
