// Code generated by MockGen. DO NOT EDIT.
// Source: shim.go

// Package mock_maintenance1 is a generated GoMock package.
package mock_maintenance1

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core1_1 "github.com/vkngwrapper/core/v2/core1_1"
)

// MockShim is a mock of Shim interface.
type MockShim struct {
	ctrl     *gomock.Controller
	recorder *MockShimMockRecorder
}

// MockShimMockRecorder is the mock recorder for MockShim.
type MockShimMockRecorder struct {
	mock *MockShim
}

// NewMockShim creates a new mock instance.
func NewMockShim(ctrl *gomock.Controller) *MockShim {
	mock := &MockShim{ctrl: ctrl}
	mock.recorder = &MockShimMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShim) EXPECT() *MockShimMockRecorder {
	return m.recorder
}

// TrimCommandPool mocks base method.
func (m *MockShim) TrimCommandPool(flags core1_1.CommandPoolTrimFlags) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrimCommandPool", flags)
}

// TrimCommandPool indicates an expected call of TrimCommandPool.
func (mr *MockShimMockRecorder) TrimCommandPool(flags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrimCommandPool", reflect.TypeOf((*MockShim)(nil).TrimCommandPool), flags)
}
