// Code generated by MockGen. DO NOT EDIT.
// Source: shim.go
//
// Generated by this command:
//
//	mockgen -source shim.go -destination ../mocks/shim.go -package mock_maintenance1
//

// Package mock_maintenance1 is a generated GoMock package.
package mock_maintenance1

import (
	reflect "reflect"

	core1_1 "github.com/vkngwrapper/core/v2/core1_1"
	gomock "go.uber.org/mock/gomock"
)

// MockShim is a mock of Shim interface.
type MockShim struct {
	ctrl     *gomock.Controller
	recorder *MockShimMockRecorder
	isgomock struct{}
}

// MockShimMockRecorder is the mock recorder for MockShim.
type MockShimMockRecorder struct {
	mock *MockShim
}

// NewMockShim creates a new mock instance.
func NewMockShim(ctrl *gomock.Controller) *MockShim {
	mock := &MockShim{ctrl: ctrl}
	mock.recorder = &MockShimMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShim) EXPECT() *MockShimMockRecorder {
	return m.recorder
}

// TrimCommandPool mocks base method.
func (m *MockShim) TrimCommandPool(flags core1_1.CommandPoolTrimFlags) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrimCommandPool", flags)
}

// TrimCommandPool indicates an expected call of TrimCommandPool.
func (mr *MockShimMockRecorder) TrimCommandPool(flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrimCommandPool", reflect.TypeOf((*MockShim)(nil).TrimCommandPool), flags)
}
