// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_draw_indirect_count
//

// Package mock_draw_indirect_count is a generated GoMock package.
package mock_draw_indirect_count

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkCmdDrawIndexedIndirectCountKHR mocks base method.
func (m *MockLoader) VkCmdDrawIndexedIndirectCountKHR(commandBuffer loader.VkCommandBuffer, buffer loader.VkBuffer, offset loader.VkDeviceSize, countBuffer loader.VkBuffer, countBufferOffset loader.VkDeviceSize, maxDrawCount, stride loader.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdDrawIndexedIndirectCountKHR", commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride)
}

// VkCmdDrawIndexedIndirectCountKHR indicates an expected call of VkCmdDrawIndexedIndirectCountKHR.
func (mr *MockLoaderMockRecorder) VkCmdDrawIndexedIndirectCountKHR(commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdDrawIndexedIndirectCountKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdDrawIndexedIndirectCountKHR), commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride)
}

// VkCmdDrawIndirectCountKHR mocks base method.
func (m *MockLoader) VkCmdDrawIndirectCountKHR(commandBuffer loader.VkCommandBuffer, buffer loader.VkBuffer, offset loader.VkDeviceSize, countBuffer loader.VkBuffer, countBufferOffset loader.VkDeviceSize, maxDrawCount, stride loader.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdDrawIndirectCountKHR", commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride)
}

// VkCmdDrawIndirectCountKHR indicates an expected call of VkCmdDrawIndirectCountKHR.
func (mr *MockLoaderMockRecorder) VkCmdDrawIndirectCountKHR(commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdDrawIndirectCountKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdDrawIndirectCountKHR), commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride)
}
