// Code generated by MockGen. DO NOT EDIT.
// Source: extension.go
//
// Generated by this command:
//
//	mockgen -source extension.go -destination ./mocks/extension.go -package mock_debugutils
//

// Package mock_debugutils is a generated GoMock package.
package mock_debugutils

import (
	reflect "reflect"

	core "github.com/vkngwrapper/core/v3"
	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	ext_debug_utils "github.com/vkngwrapper/extensions/v3/ext_debug_utils"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// CmdBeginDebugUtilsLabel mocks base method.
func (m *MockExtensionDriver) CmdBeginDebugUtilsLabel(commandBuffer core.CommandBuffer, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdBeginDebugUtilsLabel", commandBuffer, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdBeginDebugUtilsLabel indicates an expected call of CmdBeginDebugUtilsLabel.
func (mr *MockExtensionDriverMockRecorder) CmdBeginDebugUtilsLabel(commandBuffer, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdBeginDebugUtilsLabel", reflect.TypeOf((*MockExtensionDriver)(nil).CmdBeginDebugUtilsLabel), commandBuffer, label)
}

// CmdEndDebugUtilsLabel mocks base method.
func (m *MockExtensionDriver) CmdEndDebugUtilsLabel(commandBuffer core.CommandBuffer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdEndDebugUtilsLabel", commandBuffer)
}

// CmdEndDebugUtilsLabel indicates an expected call of CmdEndDebugUtilsLabel.
func (mr *MockExtensionDriverMockRecorder) CmdEndDebugUtilsLabel(commandBuffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdEndDebugUtilsLabel", reflect.TypeOf((*MockExtensionDriver)(nil).CmdEndDebugUtilsLabel), commandBuffer)
}

// CmdInsertDebugUtilsLabel mocks base method.
func (m *MockExtensionDriver) CmdInsertDebugUtilsLabel(commandBuffer core.CommandBuffer, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdInsertDebugUtilsLabel", commandBuffer, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdInsertDebugUtilsLabel indicates an expected call of CmdInsertDebugUtilsLabel.
func (mr *MockExtensionDriverMockRecorder) CmdInsertDebugUtilsLabel(commandBuffer, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdInsertDebugUtilsLabel", reflect.TypeOf((*MockExtensionDriver)(nil).CmdInsertDebugUtilsLabel), commandBuffer, label)
}

// CreateDebugUtilsMessenger mocks base method.
func (m *MockExtensionDriver) CreateDebugUtilsMessenger(allocator *loader.AllocationCallbacks, o ext_debug_utils.DebugUtilsMessengerCreateInfo) (ext_debug_utils.DebugUtilsMessenger, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDebugUtilsMessenger", allocator, o)
	ret0, _ := ret[0].(ext_debug_utils.DebugUtilsMessenger)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateDebugUtilsMessenger indicates an expected call of CreateDebugUtilsMessenger.
func (mr *MockExtensionDriverMockRecorder) CreateDebugUtilsMessenger(allocator, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDebugUtilsMessenger", reflect.TypeOf((*MockExtensionDriver)(nil).CreateDebugUtilsMessenger), allocator, o)
}

// QueueBeginDebugUtilsLabel mocks base method.
func (m *MockExtensionDriver) QueueBeginDebugUtilsLabel(queue core.Queue, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueBeginDebugUtilsLabel", queue, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueBeginDebugUtilsLabel indicates an expected call of QueueBeginDebugUtilsLabel.
func (mr *MockExtensionDriverMockRecorder) QueueBeginDebugUtilsLabel(queue, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueBeginDebugUtilsLabel", reflect.TypeOf((*MockExtensionDriver)(nil).QueueBeginDebugUtilsLabel), queue, label)
}

// QueueEndDebugUtilsLabel mocks base method.
func (m *MockExtensionDriver) QueueEndDebugUtilsLabel(queue core.Queue) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueEndDebugUtilsLabel", queue)
}

// QueueEndDebugUtilsLabel indicates an expected call of QueueEndDebugUtilsLabel.
func (mr *MockExtensionDriverMockRecorder) QueueEndDebugUtilsLabel(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueEndDebugUtilsLabel", reflect.TypeOf((*MockExtensionDriver)(nil).QueueEndDebugUtilsLabel), queue)
}

// QueueInsertDebugUtilsLabel mocks base method.
func (m *MockExtensionDriver) QueueInsertDebugUtilsLabel(queue core.Queue, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueInsertDebugUtilsLabel", queue, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueInsertDebugUtilsLabel indicates an expected call of QueueInsertDebugUtilsLabel.
func (mr *MockExtensionDriverMockRecorder) QueueInsertDebugUtilsLabel(queue, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueInsertDebugUtilsLabel", reflect.TypeOf((*MockExtensionDriver)(nil).QueueInsertDebugUtilsLabel), queue, label)
}

// SetDebugUtilsObjectName mocks base method.
func (m *MockExtensionDriver) SetDebugUtilsObjectName(device core.Device, name ext_debug_utils.DebugUtilsObjectNameInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDebugUtilsObjectName", device, name)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDebugUtilsObjectName indicates an expected call of SetDebugUtilsObjectName.
func (mr *MockExtensionDriverMockRecorder) SetDebugUtilsObjectName(device, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDebugUtilsObjectName", reflect.TypeOf((*MockExtensionDriver)(nil).SetDebugUtilsObjectName), device, name)
}

// SetDebugUtilsObjectTag mocks base method.
func (m *MockExtensionDriver) SetDebugUtilsObjectTag(device core.Device, tag ext_debug_utils.DebugUtilsObjectTagInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDebugUtilsObjectTag", device, tag)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDebugUtilsObjectTag indicates an expected call of SetDebugUtilsObjectTag.
func (mr *MockExtensionDriverMockRecorder) SetDebugUtilsObjectTag(device, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDebugUtilsObjectTag", reflect.TypeOf((*MockExtensionDriver)(nil).SetDebugUtilsObjectTag), device, tag)
}

// SubmitDebugUtilsMessage mocks base method.
func (m *MockExtensionDriver) SubmitDebugUtilsMessage(severity ext_debug_utils.DebugUtilsMessageSeverityFlags, types ext_debug_utils.DebugUtilsMessageTypeFlags, data ext_debug_utils.DebugUtilsMessengerCallbackData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitDebugUtilsMessage", severity, types, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitDebugUtilsMessage indicates an expected call of SubmitDebugUtilsMessage.
func (mr *MockExtensionDriverMockRecorder) SubmitDebugUtilsMessage(severity, types, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitDebugUtilsMessage", reflect.TypeOf((*MockExtensionDriver)(nil).SubmitDebugUtilsMessage), severity, types, data)
}
