// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_debugutils
//

// Package mock_debugutils is a generated GoMock package.
package mock_debugutils

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	ext_debug_utils_loader "github.com/vkngwrapper/extensions/v3/ext_debug_utils/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VKCmdBeginDebugUtilsLabelEXT mocks base method.
func (m *MockLoader) VKCmdBeginDebugUtilsLabelEXT(commandBuffer loader.VkCommandBuffer, pLabelInfo *ext_debug_utils_loader.VkDebugUtilsLabelEXT) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VKCmdBeginDebugUtilsLabelEXT", commandBuffer, pLabelInfo)
}

// VKCmdBeginDebugUtilsLabelEXT indicates an expected call of VKCmdBeginDebugUtilsLabelEXT.
func (mr *MockLoaderMockRecorder) VKCmdBeginDebugUtilsLabelEXT(commandBuffer, pLabelInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VKCmdBeginDebugUtilsLabelEXT", reflect.TypeOf((*MockLoader)(nil).VKCmdBeginDebugUtilsLabelEXT), commandBuffer, pLabelInfo)
}

// VkCmdEndDebugUtilsLabelEXT mocks base method.
func (m *MockLoader) VkCmdEndDebugUtilsLabelEXT(commandBuffer loader.VkCommandBuffer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdEndDebugUtilsLabelEXT", commandBuffer)
}

// VkCmdEndDebugUtilsLabelEXT indicates an expected call of VkCmdEndDebugUtilsLabelEXT.
func (mr *MockLoaderMockRecorder) VkCmdEndDebugUtilsLabelEXT(commandBuffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdEndDebugUtilsLabelEXT", reflect.TypeOf((*MockLoader)(nil).VkCmdEndDebugUtilsLabelEXT), commandBuffer)
}

// VkCmdInsertDebugUtilsLabelEXT mocks base method.
func (m *MockLoader) VkCmdInsertDebugUtilsLabelEXT(commandBuffer loader.VkCommandBuffer, pLabelInfo *ext_debug_utils_loader.VkDebugUtilsLabelEXT) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdInsertDebugUtilsLabelEXT", commandBuffer, pLabelInfo)
}

// VkCmdInsertDebugUtilsLabelEXT indicates an expected call of VkCmdInsertDebugUtilsLabelEXT.
func (mr *MockLoaderMockRecorder) VkCmdInsertDebugUtilsLabelEXT(commandBuffer, pLabelInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdInsertDebugUtilsLabelEXT", reflect.TypeOf((*MockLoader)(nil).VkCmdInsertDebugUtilsLabelEXT), commandBuffer, pLabelInfo)
}

// VkCreateDebugUtilsMessengerEXT mocks base method.
func (m *MockLoader) VkCreateDebugUtilsMessengerEXT(instance loader.VkInstance, pCreateInfo *ext_debug_utils_loader.VkDebugUtilsMessengerCreateInfoEXT, pAllocator *loader.VkAllocationCallbacks, pDebugMessenger *ext_debug_utils_loader.VkDebugUtilsMessengerEXT) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCreateDebugUtilsMessengerEXT", instance, pCreateInfo, pAllocator, pDebugMessenger)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCreateDebugUtilsMessengerEXT indicates an expected call of VkCreateDebugUtilsMessengerEXT.
func (mr *MockLoaderMockRecorder) VkCreateDebugUtilsMessengerEXT(instance, pCreateInfo, pAllocator, pDebugMessenger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCreateDebugUtilsMessengerEXT", reflect.TypeOf((*MockLoader)(nil).VkCreateDebugUtilsMessengerEXT), instance, pCreateInfo, pAllocator, pDebugMessenger)
}

// VkDestroyDebugUtilsMessengerEXT mocks base method.
func (m *MockLoader) VkDestroyDebugUtilsMessengerEXT(instance loader.VkInstance, debugMessenger ext_debug_utils_loader.VkDebugUtilsMessengerEXT, pAllocator *loader.VkAllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkDestroyDebugUtilsMessengerEXT", instance, debugMessenger, pAllocator)
}

// VkDestroyDebugUtilsMessengerEXT indicates an expected call of VkDestroyDebugUtilsMessengerEXT.
func (mr *MockLoaderMockRecorder) VkDestroyDebugUtilsMessengerEXT(instance, debugMessenger, pAllocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkDestroyDebugUtilsMessengerEXT", reflect.TypeOf((*MockLoader)(nil).VkDestroyDebugUtilsMessengerEXT), instance, debugMessenger, pAllocator)
}

// VkQueueBeginDebugUtilsLabelEXT mocks base method.
func (m *MockLoader) VkQueueBeginDebugUtilsLabelEXT(queue loader.VkQueue, pLabelInfo *ext_debug_utils_loader.VkDebugUtilsLabelEXT) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkQueueBeginDebugUtilsLabelEXT", queue, pLabelInfo)
}

// VkQueueBeginDebugUtilsLabelEXT indicates an expected call of VkQueueBeginDebugUtilsLabelEXT.
func (mr *MockLoaderMockRecorder) VkQueueBeginDebugUtilsLabelEXT(queue, pLabelInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkQueueBeginDebugUtilsLabelEXT", reflect.TypeOf((*MockLoader)(nil).VkQueueBeginDebugUtilsLabelEXT), queue, pLabelInfo)
}

// VkQueueEndDebugUtilsLabelEXT mocks base method.
func (m *MockLoader) VkQueueEndDebugUtilsLabelEXT(queue loader.VkQueue) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkQueueEndDebugUtilsLabelEXT", queue)
}

// VkQueueEndDebugUtilsLabelEXT indicates an expected call of VkQueueEndDebugUtilsLabelEXT.
func (mr *MockLoaderMockRecorder) VkQueueEndDebugUtilsLabelEXT(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkQueueEndDebugUtilsLabelEXT", reflect.TypeOf((*MockLoader)(nil).VkQueueEndDebugUtilsLabelEXT), queue)
}

// VkQueueInsertDebugUtilsLabelEXT mocks base method.
func (m *MockLoader) VkQueueInsertDebugUtilsLabelEXT(queue loader.VkQueue, pLabelInfo *ext_debug_utils_loader.VkDebugUtilsLabelEXT) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkQueueInsertDebugUtilsLabelEXT", queue, pLabelInfo)
}

// VkQueueInsertDebugUtilsLabelEXT indicates an expected call of VkQueueInsertDebugUtilsLabelEXT.
func (mr *MockLoaderMockRecorder) VkQueueInsertDebugUtilsLabelEXT(queue, pLabelInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkQueueInsertDebugUtilsLabelEXT", reflect.TypeOf((*MockLoader)(nil).VkQueueInsertDebugUtilsLabelEXT), queue, pLabelInfo)
}

// VkSetDebugUtilsObjectNameEXT mocks base method.
func (m *MockLoader) VkSetDebugUtilsObjectNameEXT(device loader.VkDevice, pNameInfo *ext_debug_utils_loader.VkDebugUtilsObjectNameInfoEXT) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkSetDebugUtilsObjectNameEXT", device, pNameInfo)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkSetDebugUtilsObjectNameEXT indicates an expected call of VkSetDebugUtilsObjectNameEXT.
func (mr *MockLoaderMockRecorder) VkSetDebugUtilsObjectNameEXT(device, pNameInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkSetDebugUtilsObjectNameEXT", reflect.TypeOf((*MockLoader)(nil).VkSetDebugUtilsObjectNameEXT), device, pNameInfo)
}

// VkSetDebugUtilsObjectTagEXT mocks base method.
func (m *MockLoader) VkSetDebugUtilsObjectTagEXT(device loader.VkDevice, pTagInfo *ext_debug_utils_loader.VkDebugUtilsObjectTagInfoEXT) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkSetDebugUtilsObjectTagEXT", device, pTagInfo)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkSetDebugUtilsObjectTagEXT indicates an expected call of VkSetDebugUtilsObjectTagEXT.
func (mr *MockLoaderMockRecorder) VkSetDebugUtilsObjectTagEXT(device, pTagInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkSetDebugUtilsObjectTagEXT", reflect.TypeOf((*MockLoader)(nil).VkSetDebugUtilsObjectTagEXT), device, pTagInfo)
}

// VkSubmitDebugUtilsMessageEXT mocks base method.
func (m *MockLoader) VkSubmitDebugUtilsMessageEXT(instance loader.VkInstance, messageSeverity ext_debug_utils_loader.VkDebugUtilsMessageSeverityFlagBitsEXT, messageTypes ext_debug_utils_loader.VkDebugUtilsMessageTypeFlagsEXT, pCallbackData *ext_debug_utils_loader.VkDebugUtilsMessengerCallbackDataEXT) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkSubmitDebugUtilsMessageEXT", instance, messageSeverity, messageTypes, pCallbackData)
}

// VkSubmitDebugUtilsMessageEXT indicates an expected call of VkSubmitDebugUtilsMessageEXT.
func (mr *MockLoaderMockRecorder) VkSubmitDebugUtilsMessageEXT(instance, messageSeverity, messageTypes, pCallbackData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkSubmitDebugUtilsMessageEXT", reflect.TypeOf((*MockLoader)(nil).VkSubmitDebugUtilsMessageEXT), instance, messageSeverity, messageTypes, pCallbackData)
}
