// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go
//
// Generated by this command:
//
//	mockgen -source driver.go -destination ../dummies/driver.go -package mock_maintenance4
//

// Package mock_maintenance4 is a generated GoMock package.
package mock_maintenance4

import (
	reflect "reflect"

	driver "github.com/vkngwrapper/core/v2/driver"
	khr_maintenance4_driver "github.com/vkngwrapper/extensions/v2/khr_maintenance4/driver"
	gomock "go.uber.org/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// VkGetDeviceBufferMemoryRequirementsKHR mocks base method.
func (m *MockDriver) VkGetDeviceBufferMemoryRequirementsKHR(device driver.VkDevice, pInfo *khr_maintenance4_driver.VkDeviceBufferMemoryRequirementsKHR, pMemoryRequirements *driver.VkMemoryRequirements2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceBufferMemoryRequirementsKHR", device, pInfo, pMemoryRequirements)
}

// VkGetDeviceBufferMemoryRequirementsKHR indicates an expected call of VkGetDeviceBufferMemoryRequirementsKHR.
func (mr *MockDriverMockRecorder) VkGetDeviceBufferMemoryRequirementsKHR(device, pInfo, pMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceBufferMemoryRequirementsKHR", reflect.TypeOf((*MockDriver)(nil).VkGetDeviceBufferMemoryRequirementsKHR), device, pInfo, pMemoryRequirements)
}

// VkGetDeviceImageMemoryRequirementsKHR mocks base method.
func (m *MockDriver) VkGetDeviceImageMemoryRequirementsKHR(device driver.VkDevice, pInfo *khr_maintenance4_driver.VkDeviceImageMemoryRequirementsKHR, pMemoryRequirements *driver.VkMemoryRequirements2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceImageMemoryRequirementsKHR", device, pInfo, pMemoryRequirements)
}

// VkGetDeviceImageMemoryRequirementsKHR indicates an expected call of VkGetDeviceImageMemoryRequirementsKHR.
func (mr *MockDriverMockRecorder) VkGetDeviceImageMemoryRequirementsKHR(device, pInfo, pMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceImageMemoryRequirementsKHR", reflect.TypeOf((*MockDriver)(nil).VkGetDeviceImageMemoryRequirementsKHR), device, pInfo, pMemoryRequirements)
}

// VkGetDeviceImageSparseMemoryRequirementsKHR mocks base method.
func (m *MockDriver) VkGetDeviceImageSparseMemoryRequirementsKHR(device driver.VkDevice, pInfo *khr_maintenance4_driver.VkDeviceImageMemoryRequirementsKHR, pSparseMemoryRequirementCount *driver.Uint32, pSparseMemoryRequirements *driver.VkSparseImageMemoryRequirements2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceImageSparseMemoryRequirementsKHR", device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
}

// VkGetDeviceImageSparseMemoryRequirementsKHR indicates an expected call of VkGetDeviceImageSparseMemoryRequirementsKHR.
func (mr *MockDriverMockRecorder) VkGetDeviceImageSparseMemoryRequirementsKHR(device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceImageSparseMemoryRequirementsKHR", reflect.TypeOf((*MockDriver)(nil).VkGetDeviceImageSparseMemoryRequirementsKHR), device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
}
