// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_dynamic_rendering
//

// Package mock_dynamic_rendering is a generated GoMock package.
package mock_dynamic_rendering

import (
	reflect "reflect"

	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_dynamic_rendering "github.com/vkngwrapper/extensions/v3/khr_dynamic_rendering"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// CmdBeginRendering mocks base method.
func (m *MockExtensionDriver) CmdBeginRendering(commandBuffer core1_0.CommandBuffer, renderingInfo khr_dynamic_rendering.RenderingInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdBeginRendering", commandBuffer, renderingInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdBeginRendering indicates an expected call of CmdBeginRendering.
func (mr *MockExtensionDriverMockRecorder) CmdBeginRendering(commandBuffer, renderingInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdBeginRendering", reflect.TypeOf((*MockExtensionDriver)(nil).CmdBeginRendering), commandBuffer, renderingInfo)
}

// CmdEndRendering mocks base method.
func (m *MockExtensionDriver) CmdEndRendering(commandBuffer core1_0.CommandBuffer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdEndRendering", commandBuffer)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdEndRendering indicates an expected call of CmdEndRendering.
func (mr *MockExtensionDriverMockRecorder) CmdEndRendering(commandBuffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdEndRendering", reflect.TypeOf((*MockExtensionDriver)(nil).CmdEndRendering), commandBuffer)
}
