// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_dynamic_rendering
//

// Package mock_dynamic_rendering is a generated GoMock package.
package mock_dynamic_rendering

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_dynamic_rendering_loader "github.com/vkngwrapper/extensions/v3/khr_dynamic_rendering/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkCmdBeginRenderingKHR mocks base method.
func (m *MockLoader) VkCmdBeginRenderingKHR(commandBuffer loader.VkCommandBuffer, pRenderingInfo *khr_dynamic_rendering_loader.VkRenderingInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdBeginRenderingKHR", commandBuffer, pRenderingInfo)
}

// VkCmdBeginRenderingKHR indicates an expected call of VkCmdBeginRenderingKHR.
func (mr *MockLoaderMockRecorder) VkCmdBeginRenderingKHR(commandBuffer, pRenderingInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdBeginRenderingKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdBeginRenderingKHR), commandBuffer, pRenderingInfo)
}

// VkCmdEndRenderingKHR mocks base method.
func (m *MockLoader) VkCmdEndRenderingKHR(commandBuffer loader.VkCommandBuffer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdEndRenderingKHR", commandBuffer)
}

// VkCmdEndRenderingKHR indicates an expected call of VkCmdEndRenderingKHR.
func (mr *MockLoaderMockRecorder) VkCmdEndRenderingKHR(commandBuffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdEndRenderingKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdEndRenderingKHR), commandBuffer)
}
