// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_get_physical_device_properties2
//

// Package mock_get_physical_device_properties2 is a generated GoMock package.
package mock_get_physical_device_properties2

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_get_physical_device_properties2 "github.com/vkngwrapper/extensions/v3/khr_get_physical_device_properties2"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// GetPhysicalDeviceFeatures2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceFeatures2(physicalDevice core1_0.PhysicalDevice, out *khr_get_physical_device_properties2.PhysicalDeviceFeatures2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceFeatures2", physicalDevice, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPhysicalDeviceFeatures2 indicates an expected call of GetPhysicalDeviceFeatures2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceFeatures2(physicalDevice, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceFeatures2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceFeatures2), physicalDevice, out)
}

// GetPhysicalDeviceFormatProperties2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceFormatProperties2(physicalDevice core1_0.PhysicalDevice, format core1_0.Format, out *khr_get_physical_device_properties2.FormatProperties2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceFormatProperties2", physicalDevice, format, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPhysicalDeviceFormatProperties2 indicates an expected call of GetPhysicalDeviceFormatProperties2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceFormatProperties2(physicalDevice, format, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceFormatProperties2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceFormatProperties2), physicalDevice, format, out)
}

// GetPhysicalDeviceImageFormatProperties2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceImageFormatProperties2(physicalDevice core1_0.PhysicalDevice, options khr_get_physical_device_properties2.PhysicalDeviceImageFormatInfo2, out *khr_get_physical_device_properties2.ImageFormatProperties2) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceImageFormatProperties2", physicalDevice, options, out)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhysicalDeviceImageFormatProperties2 indicates an expected call of GetPhysicalDeviceImageFormatProperties2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceImageFormatProperties2(physicalDevice, options, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceImageFormatProperties2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceImageFormatProperties2), physicalDevice, options, out)
}

// GetPhysicalDeviceMemoryProperties2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceMemoryProperties2(physicalDevice core1_0.PhysicalDevice, out *khr_get_physical_device_properties2.PhysicalDeviceMemoryProperties2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceMemoryProperties2", physicalDevice, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPhysicalDeviceMemoryProperties2 indicates an expected call of GetPhysicalDeviceMemoryProperties2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceMemoryProperties2(physicalDevice, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceMemoryProperties2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceMemoryProperties2), physicalDevice, out)
}

// GetPhysicalDeviceProperties2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceProperties2(physicalDevice core1_0.PhysicalDevice, out *khr_get_physical_device_properties2.PhysicalDeviceProperties2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceProperties2", physicalDevice, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPhysicalDeviceProperties2 indicates an expected call of GetPhysicalDeviceProperties2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceProperties2(physicalDevice, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceProperties2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceProperties2), physicalDevice, out)
}

// GetPhysicalDeviceQueueFamilyProperties2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceQueueFamilyProperties2(physicalDevice core1_0.PhysicalDevice, outDataFactory func() *khr_get_physical_device_properties2.QueueFamilyProperties2) ([]*khr_get_physical_device_properties2.QueueFamilyProperties2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceQueueFamilyProperties2", physicalDevice, outDataFactory)
	ret0, _ := ret[0].([]*khr_get_physical_device_properties2.QueueFamilyProperties2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhysicalDeviceQueueFamilyProperties2 indicates an expected call of GetPhysicalDeviceQueueFamilyProperties2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceQueueFamilyProperties2(physicalDevice, outDataFactory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceQueueFamilyProperties2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceQueueFamilyProperties2), physicalDevice, outDataFactory)
}

// GetPhysicalDeviceSparseImageFormatProperties2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceSparseImageFormatProperties2(physicalDevice core1_0.PhysicalDevice, options khr_get_physical_device_properties2.PhysicalDeviceSparseImageFormatInfo2, outDataFactory func() *khr_get_physical_device_properties2.SparseImageFormatProperties2) ([]*khr_get_physical_device_properties2.SparseImageFormatProperties2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceSparseImageFormatProperties2", physicalDevice, options, outDataFactory)
	ret0, _ := ret[0].([]*khr_get_physical_device_properties2.SparseImageFormatProperties2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhysicalDeviceSparseImageFormatProperties2 indicates an expected call of GetPhysicalDeviceSparseImageFormatProperties2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceSparseImageFormatProperties2(physicalDevice, options, outDataFactory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceSparseImageFormatProperties2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceSparseImageFormatProperties2), physicalDevice, options, outDataFactory)
}
