// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_timeline_semaphore
//

// Package mock_timeline_semaphore is a generated GoMock package.
package mock_timeline_semaphore

import (
	reflect "reflect"
	time "time"

	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_timeline_semaphore "github.com/vkngwrapper/extensions/v3/khr_timeline_semaphore"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// GetSemaphoreCounterValue mocks base method.
func (m *MockExtensionDriver) GetSemaphoreCounterValue(semaphore core1_0.Semaphore) (uint64, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSemaphoreCounterValue", semaphore)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSemaphoreCounterValue indicates an expected call of GetSemaphoreCounterValue.
func (mr *MockExtensionDriverMockRecorder) GetSemaphoreCounterValue(semaphore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSemaphoreCounterValue", reflect.TypeOf((*MockExtensionDriver)(nil).GetSemaphoreCounterValue), semaphore)
}

// SignalSemaphore mocks base method.
func (m *MockExtensionDriver) SignalSemaphore(o khr_timeline_semaphore.SemaphoreSignalInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalSemaphore", o)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignalSemaphore indicates an expected call of SignalSemaphore.
func (mr *MockExtensionDriverMockRecorder) SignalSemaphore(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalSemaphore", reflect.TypeOf((*MockExtensionDriver)(nil).SignalSemaphore), o)
}

// WaitSemaphores mocks base method.
func (m *MockExtensionDriver) WaitSemaphores(timeout time.Duration, o khr_timeline_semaphore.SemaphoreWaitInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitSemaphores", timeout, o)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitSemaphores indicates an expected call of WaitSemaphores.
func (mr *MockExtensionDriverMockRecorder) WaitSemaphores(timeout, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitSemaphores", reflect.TypeOf((*MockExtensionDriver)(nil).WaitSemaphores), timeout, o)
}
