// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_bind_memory2
//

// Package mock_bind_memory2 is a generated GoMock package.
package mock_bind_memory2

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_bind_memory2_loader "github.com/vkngwrapper/extensions/v3/khr_bind_memory2/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkBindBufferMemory2KHR mocks base method.
func (m *MockLoader) VkBindBufferMemory2KHR(device loader.VkDevice, bindInfoCount loader.Uint32, pBindInfos *khr_bind_memory2_loader.VkBindBufferMemoryInfoKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkBindBufferMemory2KHR", device, bindInfoCount, pBindInfos)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkBindBufferMemory2KHR indicates an expected call of VkBindBufferMemory2KHR.
func (mr *MockLoaderMockRecorder) VkBindBufferMemory2KHR(device, bindInfoCount, pBindInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkBindBufferMemory2KHR", reflect.TypeOf((*MockLoader)(nil).VkBindBufferMemory2KHR), device, bindInfoCount, pBindInfos)
}

// VkBindImageMemory2KHR mocks base method.
func (m *MockLoader) VkBindImageMemory2KHR(device loader.VkDevice, bindInfoCount loader.Uint32, pBindInfos *khr_bind_memory2_loader.VkBindImageMemoryInfoKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkBindImageMemory2KHR", device, bindInfoCount, pBindInfos)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkBindImageMemory2KHR indicates an expected call of VkBindImageMemory2KHR.
func (mr *MockLoaderMockRecorder) VkBindImageMemory2KHR(device, bindInfoCount, pBindInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkBindImageMemory2KHR", reflect.TypeOf((*MockLoader)(nil).VkBindImageMemory2KHR), device, bindInfoCount, pBindInfos)
}
