// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_acceleration_structure
//

// Package mock_acceleration_structure is a generated GoMock package.
package mock_acceleration_structure

import (
	reflect "reflect"
	unsafe "unsafe"

	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_acceleration_structure "github.com/vkngwrapper/extensions/v3/khr_acceleration_structure"
	khr_deferred_host_operations "github.com/vkngwrapper/extensions/v3/khr_deferred_host_operations"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// BuildAccelerationStructure mocks base method.
func (m *MockExtensionDriver) BuildAccelerationStructure(deferredOperation khr_deferred_host_operations.DeferredOperation, infos []khr_acceleration_structure.AccelerationStructureBuildGeometryInfo, rangeInfos [][]khr_acceleration_structure.AccelerationStructureBuildRangeInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildAccelerationStructure", deferredOperation, infos, rangeInfos)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildAccelerationStructure indicates an expected call of BuildAccelerationStructure.
func (mr *MockExtensionDriverMockRecorder) BuildAccelerationStructure(deferredOperation, infos, rangeInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildAccelerationStructure", reflect.TypeOf((*MockExtensionDriver)(nil).BuildAccelerationStructure), deferredOperation, infos, rangeInfos)
}

// CmdBuildAccelerationStructures mocks base method.
func (m *MockExtensionDriver) CmdBuildAccelerationStructures(commandBuffer core1_0.CommandBuffer, infos []khr_acceleration_structure.AccelerationStructureBuildGeometryInfo, rangeInfos [][]khr_acceleration_structure.AccelerationStructureBuildRangeInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdBuildAccelerationStructures", commandBuffer, infos, rangeInfos)
}

// CmdBuildAccelerationStructures indicates an expected call of CmdBuildAccelerationStructures.
func (mr *MockExtensionDriverMockRecorder) CmdBuildAccelerationStructures(commandBuffer, infos, rangeInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdBuildAccelerationStructures", reflect.TypeOf((*MockExtensionDriver)(nil).CmdBuildAccelerationStructures), commandBuffer, infos, rangeInfos)
}

// CmdBuildAccelerationStructuresIndirect mocks base method.
func (m *MockExtensionDriver) CmdBuildAccelerationStructuresIndirect(commandBuffer core1_0.CommandBuffer, infos []khr_acceleration_structure.AccelerationStructureBuildGeometryInfo, indirectDeviceAddresses []uint64, strides []int, maxPrimitiveCounts [][]int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdBuildAccelerationStructuresIndirect", commandBuffer, infos, indirectDeviceAddresses, strides, maxPrimitiveCounts)
}

// CmdBuildAccelerationStructuresIndirect indicates an expected call of CmdBuildAccelerationStructuresIndirect.
func (mr *MockExtensionDriverMockRecorder) CmdBuildAccelerationStructuresIndirect(commandBuffer, infos, indirectDeviceAddresses, strides, maxPrimitiveCounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdBuildAccelerationStructuresIndirect", reflect.TypeOf((*MockExtensionDriver)(nil).CmdBuildAccelerationStructuresIndirect), commandBuffer, infos, indirectDeviceAddresses, strides, maxPrimitiveCounts)
}

// CmdCopyAccelerationStructure mocks base method.
func (m *MockExtensionDriver) CmdCopyAccelerationStructure(commandBuffer core1_0.CommandBuffer, info khr_acceleration_structure.CopyAccelerationStructureInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdCopyAccelerationStructure", commandBuffer, info)
}

// CmdCopyAccelerationStructure indicates an expected call of CmdCopyAccelerationStructure.
func (mr *MockExtensionDriverMockRecorder) CmdCopyAccelerationStructure(commandBuffer, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdCopyAccelerationStructure", reflect.TypeOf((*MockExtensionDriver)(nil).CmdCopyAccelerationStructure), commandBuffer, info)
}

// CmdCopyAccelerationStructureToMemory mocks base method.
func (m *MockExtensionDriver) CmdCopyAccelerationStructureToMemory(commandBuffer core1_0.CommandBuffer, info khr_acceleration_structure.CopyAccelerationStructureToMemoryInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdCopyAccelerationStructureToMemory", commandBuffer, info)
}

// CmdCopyAccelerationStructureToMemory indicates an expected call of CmdCopyAccelerationStructureToMemory.
func (mr *MockExtensionDriverMockRecorder) CmdCopyAccelerationStructureToMemory(commandBuffer, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdCopyAccelerationStructureToMemory", reflect.TypeOf((*MockExtensionDriver)(nil).CmdCopyAccelerationStructureToMemory), commandBuffer, info)
}

// CmdCopyMemoryToAccelerationStructure mocks base method.
func (m *MockExtensionDriver) CmdCopyMemoryToAccelerationStructure(commandBuffer core1_0.CommandBuffer, info khr_acceleration_structure.CopyMemoryToAccelerationStructureInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdCopyMemoryToAccelerationStructure", commandBuffer, info)
}

// CmdCopyMemoryToAccelerationStructure indicates an expected call of CmdCopyMemoryToAccelerationStructure.
func (mr *MockExtensionDriverMockRecorder) CmdCopyMemoryToAccelerationStructure(commandBuffer, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdCopyMemoryToAccelerationStructure", reflect.TypeOf((*MockExtensionDriver)(nil).CmdCopyMemoryToAccelerationStructure), commandBuffer, info)
}

// CmdWriteAccelerationStructuresProperties mocks base method.
func (m *MockExtensionDriver) CmdWriteAccelerationStructuresProperties(commandBuffer core1_0.CommandBuffer, accelerationStructures []khr_acceleration_structure.AccelerationStructure, queryType core1_0.QueryType, queryPool core1_0.QueryPool, firstQuery int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdWriteAccelerationStructuresProperties", commandBuffer, accelerationStructures, queryType, queryPool, firstQuery)
}

// CmdWriteAccelerationStructuresProperties indicates an expected call of CmdWriteAccelerationStructuresProperties.
func (mr *MockExtensionDriverMockRecorder) CmdWriteAccelerationStructuresProperties(commandBuffer, accelerationStructures, queryType, queryPool, firstQuery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdWriteAccelerationStructuresProperties", reflect.TypeOf((*MockExtensionDriver)(nil).CmdWriteAccelerationStructuresProperties), commandBuffer, accelerationStructures, queryType, queryPool, firstQuery)
}

// CopyAccelerationStructure mocks base method.
func (m *MockExtensionDriver) CopyAccelerationStructure(deferredOperation khr_deferred_host_operations.DeferredOperation, info khr_acceleration_structure.CopyAccelerationStructureInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyAccelerationStructure", deferredOperation, info)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyAccelerationStructure indicates an expected call of CopyAccelerationStructure.
func (mr *MockExtensionDriverMockRecorder) CopyAccelerationStructure(deferredOperation, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyAccelerationStructure", reflect.TypeOf((*MockExtensionDriver)(nil).CopyAccelerationStructure), deferredOperation, info)
}

// CopyAccelerationStructureToMemory mocks base method.
func (m *MockExtensionDriver) CopyAccelerationStructureToMemory(deferredOperation khr_deferred_host_operations.DeferredOperation, info khr_acceleration_structure.CopyAccelerationStructureToMemoryInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyAccelerationStructureToMemory", deferredOperation, info)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyAccelerationStructureToMemory indicates an expected call of CopyAccelerationStructureToMemory.
func (mr *MockExtensionDriverMockRecorder) CopyAccelerationStructureToMemory(deferredOperation, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyAccelerationStructureToMemory", reflect.TypeOf((*MockExtensionDriver)(nil).CopyAccelerationStructureToMemory), deferredOperation, info)
}

// CopyMemoryToAccelerationStructure mocks base method.
func (m *MockExtensionDriver) CopyMemoryToAccelerationStructure(deferredOperation khr_deferred_host_operations.DeferredOperation, info khr_acceleration_structure.CopyMemoryToAccelerationStructureInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyMemoryToAccelerationStructure", deferredOperation, info)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyMemoryToAccelerationStructure indicates an expected call of CopyMemoryToAccelerationStructure.
func (mr *MockExtensionDriverMockRecorder) CopyMemoryToAccelerationStructure(deferredOperation, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyMemoryToAccelerationStructure", reflect.TypeOf((*MockExtensionDriver)(nil).CopyMemoryToAccelerationStructure), deferredOperation, info)
}

// CreateAccelerationStructure mocks base method.
func (m *MockExtensionDriver) CreateAccelerationStructure(createInfo khr_acceleration_structure.AccelerationStructureCreateInfo, allocator *loader.AllocationCallbacks) (khr_acceleration_structure.AccelerationStructure, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccelerationStructure", createInfo, allocator)
	ret0, _ := ret[0].(khr_acceleration_structure.AccelerationStructure)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAccelerationStructure indicates an expected call of CreateAccelerationStructure.
func (mr *MockExtensionDriverMockRecorder) CreateAccelerationStructure(createInfo, allocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccelerationStructure", reflect.TypeOf((*MockExtensionDriver)(nil).CreateAccelerationStructure), createInfo, allocator)
}

// DestroyAccelerationStructure mocks base method.
func (m *MockExtensionDriver) DestroyAccelerationStructure(accelerationStructure khr_acceleration_structure.AccelerationStructure, pAllocator *loader.AllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DestroyAccelerationStructure", accelerationStructure, pAllocator)
}

// DestroyAccelerationStructure indicates an expected call of DestroyAccelerationStructure.
func (mr *MockExtensionDriverMockRecorder) DestroyAccelerationStructure(accelerationStructure, pAllocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyAccelerationStructure", reflect.TypeOf((*MockExtensionDriver)(nil).DestroyAccelerationStructure), accelerationStructure, pAllocator)
}

// GetAccelerationStructureBuildSizes mocks base method.
func (m *MockExtensionDriver) GetAccelerationStructureBuildSizes(buildType khr_acceleration_structure.AccelerationStructureBuildType, buildInfo khr_acceleration_structure.AccelerationStructureBuildGeometryInfo, maxPrimitiveCounts []int, out *khr_acceleration_structure.AccelerationStructureBuildSizesInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAccelerationStructureBuildSizes", buildType, buildInfo, maxPrimitiveCounts, out)
}

// GetAccelerationStructureBuildSizes indicates an expected call of GetAccelerationStructureBuildSizes.
func (mr *MockExtensionDriverMockRecorder) GetAccelerationStructureBuildSizes(buildType, buildInfo, maxPrimitiveCounts, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccelerationStructureBuildSizes", reflect.TypeOf((*MockExtensionDriver)(nil).GetAccelerationStructureBuildSizes), buildType, buildInfo, maxPrimitiveCounts, out)
}

// GetAccelerationStructureDeviceAddress mocks base method.
func (m *MockExtensionDriver) GetAccelerationStructureDeviceAddress(o khr_acceleration_structure.AccelerationStructureDeviceAddressInfo) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccelerationStructureDeviceAddress", o)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetAccelerationStructureDeviceAddress indicates an expected call of GetAccelerationStructureDeviceAddress.
func (mr *MockExtensionDriverMockRecorder) GetAccelerationStructureDeviceAddress(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccelerationStructureDeviceAddress", reflect.TypeOf((*MockExtensionDriver)(nil).GetAccelerationStructureDeviceAddress), o)
}

// GetDeviceAccelerationStructureCompatibility mocks base method.
func (m *MockExtensionDriver) GetDeviceAccelerationStructureCompatibility(o khr_acceleration_structure.AccelerationStructureVersionInfo) khr_acceleration_structure.AccelerationStructureCompatibility {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceAccelerationStructureCompatibility", o)
	ret0, _ := ret[0].(khr_acceleration_structure.AccelerationStructureCompatibility)
	return ret0
}

// GetDeviceAccelerationStructureCompatibility indicates an expected call of GetDeviceAccelerationStructureCompatibility.
func (mr *MockExtensionDriverMockRecorder) GetDeviceAccelerationStructureCompatibility(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceAccelerationStructureCompatibility", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeviceAccelerationStructureCompatibility), o)
}

// WriteAccelerationStructuresProperties mocks base method.
func (m *MockExtensionDriver) WriteAccelerationStructuresProperties(accelerationStructures []khr_acceleration_structure.AccelerationStructure, queryType core1_0.QueryType, dataSize int, data unsafe.Pointer, stride int) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAccelerationStructuresProperties", accelerationStructures, queryType, dataSize, data, stride)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteAccelerationStructuresProperties indicates an expected call of WriteAccelerationStructuresProperties.
func (mr *MockExtensionDriverMockRecorder) WriteAccelerationStructuresProperties(accelerationStructures, queryType, dataSize, data, stride any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAccelerationStructuresProperties", reflect.TypeOf((*MockExtensionDriver)(nil).WriteAccelerationStructuresProperties), accelerationStructures, queryType, dataSize, data, stride)
}
