// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_acceleration_structure
//

// Package mock_acceleration_structure is a generated GoMock package.
package mock_acceleration_structure

import (
	reflect "reflect"
	unsafe "unsafe"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_acceleration_structure_loader "github.com/vkngwrapper/extensions/v3/khr_acceleration_structure/loader"
	khr_deferred_host_operations_loader "github.com/vkngwrapper/extensions/v3/khr_deferred_host_operations/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkBuildAccelerationStructuresKHR mocks base method.
func (m *MockLoader) VkBuildAccelerationStructuresKHR(device loader.VkDevice, deferredOperation khr_deferred_host_operations_loader.VkDeferredOperationKHR, infoCount loader.Uint32, pInfos *khr_acceleration_structure_loader.VkAccelerationStructureBuildGeometryInfoKHR, ppBuildRangeInfos **khr_acceleration_structure_loader.VkAccelerationStructureBuildRangeInfoKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkBuildAccelerationStructuresKHR", device, deferredOperation, infoCount, pInfos, ppBuildRangeInfos)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkBuildAccelerationStructuresKHR indicates an expected call of VkBuildAccelerationStructuresKHR.
func (mr *MockLoaderMockRecorder) VkBuildAccelerationStructuresKHR(device, deferredOperation, infoCount, pInfos, ppBuildRangeInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkBuildAccelerationStructuresKHR", reflect.TypeOf((*MockLoader)(nil).VkBuildAccelerationStructuresKHR), device, deferredOperation, infoCount, pInfos, ppBuildRangeInfos)
}

// VkCmdBuildAccelerationStructuresIndirectKHR mocks base method.
func (m *MockLoader) VkCmdBuildAccelerationStructuresIndirectKHR(commandBuffer loader.VkCommandBuffer, infoCount loader.Uint32, pInfos *khr_acceleration_structure_loader.VkAccelerationStructureBuildGeometryInfoKHR, pIndirectDeviceAddresses *loader.VkDeviceAddress, pIndirectStrides *loader.Uint32, ppMaxPrimitiveCountws **loader.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdBuildAccelerationStructuresIndirectKHR", commandBuffer, infoCount, pInfos, pIndirectDeviceAddresses, pIndirectStrides, ppMaxPrimitiveCountws)
}

// VkCmdBuildAccelerationStructuresIndirectKHR indicates an expected call of VkCmdBuildAccelerationStructuresIndirectKHR.
func (mr *MockLoaderMockRecorder) VkCmdBuildAccelerationStructuresIndirectKHR(commandBuffer, infoCount, pInfos, pIndirectDeviceAddresses, pIndirectStrides, ppMaxPrimitiveCountws any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdBuildAccelerationStructuresIndirectKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdBuildAccelerationStructuresIndirectKHR), commandBuffer, infoCount, pInfos, pIndirectDeviceAddresses, pIndirectStrides, ppMaxPrimitiveCountws)
}

// VkCmdBuildAccelerationStructuresKHR mocks base method.
func (m *MockLoader) VkCmdBuildAccelerationStructuresKHR(commandBuffer loader.VkCommandBuffer, infoCount loader.Uint32, pInfos *khr_acceleration_structure_loader.VkAccelerationStructureBuildGeometryInfoKHR, ppBuildRangeInfos **khr_acceleration_structure_loader.VkAccelerationStructureBuildRangeInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdBuildAccelerationStructuresKHR", commandBuffer, infoCount, pInfos, ppBuildRangeInfos)
}

// VkCmdBuildAccelerationStructuresKHR indicates an expected call of VkCmdBuildAccelerationStructuresKHR.
func (mr *MockLoaderMockRecorder) VkCmdBuildAccelerationStructuresKHR(commandBuffer, infoCount, pInfos, ppBuildRangeInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdBuildAccelerationStructuresKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdBuildAccelerationStructuresKHR), commandBuffer, infoCount, pInfos, ppBuildRangeInfos)
}

// VkCmdCopyAccelerationStructureKHR mocks base method.
func (m *MockLoader) VkCmdCopyAccelerationStructureKHR(commandBuffer loader.VkCommandBuffer, pInfo *khr_acceleration_structure_loader.VkCopyAccelerationStructureInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdCopyAccelerationStructureKHR", commandBuffer, pInfo)
}

// VkCmdCopyAccelerationStructureKHR indicates an expected call of VkCmdCopyAccelerationStructureKHR.
func (mr *MockLoaderMockRecorder) VkCmdCopyAccelerationStructureKHR(commandBuffer, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdCopyAccelerationStructureKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdCopyAccelerationStructureKHR), commandBuffer, pInfo)
}

// VkCmdCopyAccelerationStructureToMemoryKHR mocks base method.
func (m *MockLoader) VkCmdCopyAccelerationStructureToMemoryKHR(commandBuffer loader.VkCommandBuffer, pInfo *khr_acceleration_structure_loader.VkCopyAccelerationStructureToMemoryInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdCopyAccelerationStructureToMemoryKHR", commandBuffer, pInfo)
}

// VkCmdCopyAccelerationStructureToMemoryKHR indicates an expected call of VkCmdCopyAccelerationStructureToMemoryKHR.
func (mr *MockLoaderMockRecorder) VkCmdCopyAccelerationStructureToMemoryKHR(commandBuffer, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdCopyAccelerationStructureToMemoryKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdCopyAccelerationStructureToMemoryKHR), commandBuffer, pInfo)
}

// VkCmdCopyMemoryToAccelerationStructureKHR mocks base method.
func (m *MockLoader) VkCmdCopyMemoryToAccelerationStructureKHR(commandBuffer loader.VkCommandBuffer, pInfo *khr_acceleration_structure_loader.VkCopyMemoryToAccelerationStructureInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdCopyMemoryToAccelerationStructureKHR", commandBuffer, pInfo)
}

// VkCmdCopyMemoryToAccelerationStructureKHR indicates an expected call of VkCmdCopyMemoryToAccelerationStructureKHR.
func (mr *MockLoaderMockRecorder) VkCmdCopyMemoryToAccelerationStructureKHR(commandBuffer, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdCopyMemoryToAccelerationStructureKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdCopyMemoryToAccelerationStructureKHR), commandBuffer, pInfo)
}

// VkCmdWriteAccelerationStructuresPropertiesKHR mocks base method.
func (m *MockLoader) VkCmdWriteAccelerationStructuresPropertiesKHR(commandBuffer loader.VkCommandBuffer, accelerationStructureCount loader.Uint32, pAccelerationStructures *khr_acceleration_structure_loader.VkAccelerationStructureKHR, queryType loader.VkQueryType, queryPool loader.VkQueryPool, firstQuery loader.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdWriteAccelerationStructuresPropertiesKHR", commandBuffer, accelerationStructureCount, pAccelerationStructures, queryType, queryPool, firstQuery)
}

// VkCmdWriteAccelerationStructuresPropertiesKHR indicates an expected call of VkCmdWriteAccelerationStructuresPropertiesKHR.
func (mr *MockLoaderMockRecorder) VkCmdWriteAccelerationStructuresPropertiesKHR(commandBuffer, accelerationStructureCount, pAccelerationStructures, queryType, queryPool, firstQuery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdWriteAccelerationStructuresPropertiesKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdWriteAccelerationStructuresPropertiesKHR), commandBuffer, accelerationStructureCount, pAccelerationStructures, queryType, queryPool, firstQuery)
}

// VkCopyAccelerationStructureKHR mocks base method.
func (m *MockLoader) VkCopyAccelerationStructureKHR(device loader.VkDevice, deferredOperation khr_deferred_host_operations_loader.VkDeferredOperationKHR, pInfo *khr_acceleration_structure_loader.VkCopyAccelerationStructureInfoKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCopyAccelerationStructureKHR", device, deferredOperation, pInfo)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCopyAccelerationStructureKHR indicates an expected call of VkCopyAccelerationStructureKHR.
func (mr *MockLoaderMockRecorder) VkCopyAccelerationStructureKHR(device, deferredOperation, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCopyAccelerationStructureKHR", reflect.TypeOf((*MockLoader)(nil).VkCopyAccelerationStructureKHR), device, deferredOperation, pInfo)
}

// VkCopyAccelerationStructureToMemoryKHR mocks base method.
func (m *MockLoader) VkCopyAccelerationStructureToMemoryKHR(device loader.VkDevice, deferredOperation khr_deferred_host_operations_loader.VkDeferredOperationKHR, pInfo *khr_acceleration_structure_loader.VkCopyAccelerationStructureToMemoryInfoKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCopyAccelerationStructureToMemoryKHR", device, deferredOperation, pInfo)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCopyAccelerationStructureToMemoryKHR indicates an expected call of VkCopyAccelerationStructureToMemoryKHR.
func (mr *MockLoaderMockRecorder) VkCopyAccelerationStructureToMemoryKHR(device, deferredOperation, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCopyAccelerationStructureToMemoryKHR", reflect.TypeOf((*MockLoader)(nil).VkCopyAccelerationStructureToMemoryKHR), device, deferredOperation, pInfo)
}

// VkCopyMemoryToAccelerationStructureKHR mocks base method.
func (m *MockLoader) VkCopyMemoryToAccelerationStructureKHR(device loader.VkDevice, deferredOperation khr_deferred_host_operations_loader.VkDeferredOperationKHR, pInfo *khr_acceleration_structure_loader.VkCopyMemoryToAccelerationStructureInfoKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCopyMemoryToAccelerationStructureKHR", device, deferredOperation, pInfo)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCopyMemoryToAccelerationStructureKHR indicates an expected call of VkCopyMemoryToAccelerationStructureKHR.
func (mr *MockLoaderMockRecorder) VkCopyMemoryToAccelerationStructureKHR(device, deferredOperation, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCopyMemoryToAccelerationStructureKHR", reflect.TypeOf((*MockLoader)(nil).VkCopyMemoryToAccelerationStructureKHR), device, deferredOperation, pInfo)
}

// VkCreateAccelerationStructureKHR mocks base method.
func (m *MockLoader) VkCreateAccelerationStructureKHR(device loader.VkDevice, pCreateInfo *khr_acceleration_structure_loader.VkAccelerationStructureCreateInfoKHR, pAllocator *loader.VkAllocationCallbacks, pAccelerationStructure *khr_acceleration_structure_loader.VkAccelerationStructureKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCreateAccelerationStructureKHR", device, pCreateInfo, pAllocator, pAccelerationStructure)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCreateAccelerationStructureKHR indicates an expected call of VkCreateAccelerationStructureKHR.
func (mr *MockLoaderMockRecorder) VkCreateAccelerationStructureKHR(device, pCreateInfo, pAllocator, pAccelerationStructure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCreateAccelerationStructureKHR", reflect.TypeOf((*MockLoader)(nil).VkCreateAccelerationStructureKHR), device, pCreateInfo, pAllocator, pAccelerationStructure)
}

// VkDestroyAccelerationStructureKHR mocks base method.
func (m *MockLoader) VkDestroyAccelerationStructureKHR(device loader.VkDevice, accelerationStructure khr_acceleration_structure_loader.VkAccelerationStructureKHR, pAllocator *loader.VkAllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkDestroyAccelerationStructureKHR", device, accelerationStructure, pAllocator)
}

// VkDestroyAccelerationStructureKHR indicates an expected call of VkDestroyAccelerationStructureKHR.
func (mr *MockLoaderMockRecorder) VkDestroyAccelerationStructureKHR(device, accelerationStructure, pAllocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkDestroyAccelerationStructureKHR", reflect.TypeOf((*MockLoader)(nil).VkDestroyAccelerationStructureKHR), device, accelerationStructure, pAllocator)
}

// VkGetAccelerationStructureBuildSizesKHR mocks base method.
func (m *MockLoader) VkGetAccelerationStructureBuildSizesKHR(device loader.VkDevice, buildType khr_acceleration_structure_loader.VkAccelerationStructureBuildTypeKHR, pBuildInfo *khr_acceleration_structure_loader.VkAccelerationStructureBuildGeometryInfoKHR, pMaxPrimitiveCounts *loader.Uint32, pSizeInfo *khr_acceleration_structure_loader.VkAccelerationStructureBuildSizesInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetAccelerationStructureBuildSizesKHR", device, buildType, pBuildInfo, pMaxPrimitiveCounts, pSizeInfo)
}

// VkGetAccelerationStructureBuildSizesKHR indicates an expected call of VkGetAccelerationStructureBuildSizesKHR.
func (mr *MockLoaderMockRecorder) VkGetAccelerationStructureBuildSizesKHR(device, buildType, pBuildInfo, pMaxPrimitiveCounts, pSizeInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetAccelerationStructureBuildSizesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetAccelerationStructureBuildSizesKHR), device, buildType, pBuildInfo, pMaxPrimitiveCounts, pSizeInfo)
}

// VkGetAccelerationStructureDeviceAddressKHR mocks base method.
func (m *MockLoader) VkGetAccelerationStructureDeviceAddressKHR(device loader.VkDevice, pInfo *khr_acceleration_structure_loader.VkAccelerationStructureDeviceAddressInfoKHR) loader.VkDeviceAddress {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetAccelerationStructureDeviceAddressKHR", device, pInfo)
	ret0, _ := ret[0].(loader.VkDeviceAddress)
	return ret0
}

// VkGetAccelerationStructureDeviceAddressKHR indicates an expected call of VkGetAccelerationStructureDeviceAddressKHR.
func (mr *MockLoaderMockRecorder) VkGetAccelerationStructureDeviceAddressKHR(device, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetAccelerationStructureDeviceAddressKHR", reflect.TypeOf((*MockLoader)(nil).VkGetAccelerationStructureDeviceAddressKHR), device, pInfo)
}

// VkGetDeviceAccelerationStructureCompatibilityKHR mocks base method.
func (m *MockLoader) VkGetDeviceAccelerationStructureCompatibilityKHR(device loader.VkDevice, pVersionInfo *khr_acceleration_structure_loader.VkAccelerationStructureVersionInfoKHR, pCompatibility *khr_acceleration_structure_loader.VkAccelerationStructureCompatibilityKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDeviceAccelerationStructureCompatibilityKHR", device, pVersionInfo, pCompatibility)
}

// VkGetDeviceAccelerationStructureCompatibilityKHR indicates an expected call of VkGetDeviceAccelerationStructureCompatibilityKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceAccelerationStructureCompatibilityKHR(device, pVersionInfo, pCompatibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceAccelerationStructureCompatibilityKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceAccelerationStructureCompatibilityKHR), device, pVersionInfo, pCompatibility)
}

// VkWriteAccelerationStructuresPropertiesKHR mocks base method.
func (m *MockLoader) VkWriteAccelerationStructuresPropertiesKHR(device loader.VkDevice, accelerationStructureCount loader.Uint32, pAccelerationStructures *khr_acceleration_structure_loader.VkAccelerationStructureKHR, queryType loader.VkQueryType, dataSize loader.Size, pData unsafe.Pointer, stride loader.Size) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkWriteAccelerationStructuresPropertiesKHR", device, accelerationStructureCount, pAccelerationStructures, queryType, dataSize, pData, stride)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkWriteAccelerationStructuresPropertiesKHR indicates an expected call of VkWriteAccelerationStructuresPropertiesKHR.
func (mr *MockLoaderMockRecorder) VkWriteAccelerationStructuresPropertiesKHR(device, accelerationStructureCount, pAccelerationStructures, queryType, dataSize, pData, stride any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkWriteAccelerationStructuresPropertiesKHR", reflect.TypeOf((*MockLoader)(nil).VkWriteAccelerationStructuresPropertiesKHR), device, accelerationStructureCount, pAccelerationStructures, queryType, dataSize, pData, stride)
}
