// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_deferred_host_operations
//

// Package mock_deferred_host_operations is a generated GoMock package.
package mock_deferred_host_operations

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_deferred_host_operations "github.com/vkngwrapper/extensions/v3/khr_deferred_host_operations"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// CreateDeferredOperation mocks base method.
func (m *MockExtensionDriver) CreateDeferredOperation(callbacks *loader.AllocationCallbacks) (khr_deferred_host_operations.DeferredOperation, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeferredOperation", callbacks)
	ret0, _ := ret[0].(khr_deferred_host_operations.DeferredOperation)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateDeferredOperation indicates an expected call of CreateDeferredOperation.
func (mr *MockExtensionDriverMockRecorder) CreateDeferredOperation(callbacks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeferredOperation", reflect.TypeOf((*MockExtensionDriver)(nil).CreateDeferredOperation), callbacks)
}

// DeferredOperationJoin mocks base method.
func (m *MockExtensionDriver) DeferredOperationJoin(operation khr_deferred_host_operations.DeferredOperation) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeferredOperationJoin", operation)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeferredOperationJoin indicates an expected call of DeferredOperationJoin.
func (mr *MockExtensionDriverMockRecorder) DeferredOperationJoin(operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeferredOperationJoin", reflect.TypeOf((*MockExtensionDriver)(nil).DeferredOperationJoin), operation)
}

// DestroyDeferredOperation mocks base method.
func (m *MockExtensionDriver) DestroyDeferredOperation(operation khr_deferred_host_operations.DeferredOperation, callbacks *loader.AllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DestroyDeferredOperation", operation, callbacks)
}

// DestroyDeferredOperation indicates an expected call of DestroyDeferredOperation.
func (mr *MockExtensionDriverMockRecorder) DestroyDeferredOperation(operation, callbacks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyDeferredOperation", reflect.TypeOf((*MockExtensionDriver)(nil).DestroyDeferredOperation), operation, callbacks)
}

// GetDeferredOperationMaxConcurrency mocks base method.
func (m *MockExtensionDriver) GetDeferredOperationMaxConcurrency(operation khr_deferred_host_operations.DeferredOperation) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeferredOperationMaxConcurrency", operation)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetDeferredOperationMaxConcurrency indicates an expected call of GetDeferredOperationMaxConcurrency.
func (mr *MockExtensionDriverMockRecorder) GetDeferredOperationMaxConcurrency(operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeferredOperationMaxConcurrency", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeferredOperationMaxConcurrency), operation)
}

// GetDeferredOperationResult mocks base method.
func (m *MockExtensionDriver) GetDeferredOperationResult(operation khr_deferred_host_operations.DeferredOperation) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeferredOperationResult", operation)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeferredOperationResult indicates an expected call of GetDeferredOperationResult.
func (mr *MockExtensionDriverMockRecorder) GetDeferredOperationResult(operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeferredOperationResult", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeferredOperationResult), operation)
}
