// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_deferred_host_operations
//

// Package mock_deferred_host_operations is a generated GoMock package.
package mock_deferred_host_operations

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_deferred_host_operations_loader "github.com/vkngwrapper/extensions/v3/khr_deferred_host_operations/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkCreateDeferredOperationKHR mocks base method.
func (m *MockLoader) VkCreateDeferredOperationKHR(device loader.VkDevice, pAllocator *loader.VkAllocationCallbacks, pDeferredOperation *khr_deferred_host_operations_loader.VkDeferredOperationKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCreateDeferredOperationKHR", device, pAllocator, pDeferredOperation)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCreateDeferredOperationKHR indicates an expected call of VkCreateDeferredOperationKHR.
func (mr *MockLoaderMockRecorder) VkCreateDeferredOperationKHR(device, pAllocator, pDeferredOperation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCreateDeferredOperationKHR", reflect.TypeOf((*MockLoader)(nil).VkCreateDeferredOperationKHR), device, pAllocator, pDeferredOperation)
}

// VkDeferredOperationJoinKHR mocks base method.
func (m *MockLoader) VkDeferredOperationJoinKHR(device loader.VkDevice, operation khr_deferred_host_operations_loader.VkDeferredOperationKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkDeferredOperationJoinKHR", device, operation)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkDeferredOperationJoinKHR indicates an expected call of VkDeferredOperationJoinKHR.
func (mr *MockLoaderMockRecorder) VkDeferredOperationJoinKHR(device, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkDeferredOperationJoinKHR", reflect.TypeOf((*MockLoader)(nil).VkDeferredOperationJoinKHR), device, operation)
}

// VkDestroyDeferredOperationKHR mocks base method.
func (m *MockLoader) VkDestroyDeferredOperationKHR(device loader.VkDevice, operation khr_deferred_host_operations_loader.VkDeferredOperationKHR, pAllocator *loader.VkAllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkDestroyDeferredOperationKHR", device, operation, pAllocator)
}

// VkDestroyDeferredOperationKHR indicates an expected call of VkDestroyDeferredOperationKHR.
func (mr *MockLoaderMockRecorder) VkDestroyDeferredOperationKHR(device, operation, pAllocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkDestroyDeferredOperationKHR", reflect.TypeOf((*MockLoader)(nil).VkDestroyDeferredOperationKHR), device, operation, pAllocator)
}

// VkGetDeferredOperationMaxConcurrencyKHR mocks base method.
func (m *MockLoader) VkGetDeferredOperationMaxConcurrencyKHR(device loader.VkDevice, operation khr_deferred_host_operations_loader.VkDeferredOperationKHR) loader.Uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeferredOperationMaxConcurrencyKHR", device, operation)
	ret0, _ := ret[0].(loader.Uint32)
	return ret0
}

// VkGetDeferredOperationMaxConcurrencyKHR indicates an expected call of VkGetDeferredOperationMaxConcurrencyKHR.
func (mr *MockLoaderMockRecorder) VkGetDeferredOperationMaxConcurrencyKHR(device, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeferredOperationMaxConcurrencyKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeferredOperationMaxConcurrencyKHR), device, operation)
}

// VkGetDeferredOperationResultKHR mocks base method.
func (m *MockLoader) VkGetDeferredOperationResultKHR(device loader.VkDevice, operation khr_deferred_host_operations_loader.VkDeferredOperationKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeferredOperationResultKHR", device, operation)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetDeferredOperationResultKHR indicates an expected call of VkGetDeferredOperationResultKHR.
func (mr *MockLoaderMockRecorder) VkGetDeferredOperationResultKHR(device, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeferredOperationResultKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeferredOperationResultKHR), device, operation)
}
