// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_buffer_device_address
//

// Package mock_buffer_device_address is a generated GoMock package.
package mock_buffer_device_address

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_buffer_device_address_loader "github.com/vkngwrapper/extensions/v3/khr_buffer_device_address/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkGetBufferDeviceAddressKHR mocks base method.
func (m *MockLoader) VkGetBufferDeviceAddressKHR(device loader.VkDevice, pInfo *khr_buffer_device_address_loader.VkBufferDeviceAddressInfoKHR) loader.VkDeviceAddress {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetBufferDeviceAddressKHR", device, pInfo)
	ret0, _ := ret[0].(loader.VkDeviceAddress)
	return ret0
}

// VkGetBufferDeviceAddressKHR indicates an expected call of VkGetBufferDeviceAddressKHR.
func (mr *MockLoaderMockRecorder) VkGetBufferDeviceAddressKHR(device, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetBufferDeviceAddressKHR", reflect.TypeOf((*MockLoader)(nil).VkGetBufferDeviceAddressKHR), device, pInfo)
}

// VkGetBufferOpaqueCaptureAddressKHR mocks base method.
func (m *MockLoader) VkGetBufferOpaqueCaptureAddressKHR(device loader.VkDevice, pInfo *khr_buffer_device_address_loader.VkBufferDeviceAddressInfoKHR) loader.Uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetBufferOpaqueCaptureAddressKHR", device, pInfo)
	ret0, _ := ret[0].(loader.Uint64)
	return ret0
}

// VkGetBufferOpaqueCaptureAddressKHR indicates an expected call of VkGetBufferOpaqueCaptureAddressKHR.
func (mr *MockLoaderMockRecorder) VkGetBufferOpaqueCaptureAddressKHR(device, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetBufferOpaqueCaptureAddressKHR", reflect.TypeOf((*MockLoader)(nil).VkGetBufferOpaqueCaptureAddressKHR), device, pInfo)
}

// VkGetDeviceMemoryOpaqueCaptureAddressKHR mocks base method.
func (m *MockLoader) VkGetDeviceMemoryOpaqueCaptureAddressKHR(device loader.VkDevice, pInfo *khr_buffer_device_address_loader.VkDeviceMemoryOpaqueCaptureAddressInfoKHR) loader.Uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeviceMemoryOpaqueCaptureAddressKHR", device, pInfo)
	ret0, _ := ret[0].(loader.Uint64)
	return ret0
}

// VkGetDeviceMemoryOpaqueCaptureAddressKHR indicates an expected call of VkGetDeviceMemoryOpaqueCaptureAddressKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceMemoryOpaqueCaptureAddressKHR(device, pInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceMemoryOpaqueCaptureAddressKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceMemoryOpaqueCaptureAddressKHR), device, pInfo)
}
