// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_external_semaphore_capabilities
//

// Package mock_external_semaphore_capabilities is a generated GoMock package.
package mock_external_semaphore_capabilities

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_external_semaphore_capabilities_loader "github.com/vkngwrapper/extensions/v3/khr_external_semaphore_capabilities/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkGetPhysicalDeviceExternalSemaphorePropertiesKHR mocks base method.
func (m *MockLoader) VkGetPhysicalDeviceExternalSemaphorePropertiesKHR(physicalDevice loader.VkPhysicalDevice, pExternalSemaphoreInfo *khr_external_semaphore_capabilities_loader.VkPhysicalDeviceExternalSemaphoreInfoKHR, pExternalSemaphoreProperties *khr_external_semaphore_capabilities_loader.VkExternalSemaphorePropertiesKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetPhysicalDeviceExternalSemaphorePropertiesKHR", physicalDevice, pExternalSemaphoreInfo, pExternalSemaphoreProperties)
}

// VkGetPhysicalDeviceExternalSemaphorePropertiesKHR indicates an expected call of VkGetPhysicalDeviceExternalSemaphorePropertiesKHR.
func (mr *MockLoaderMockRecorder) VkGetPhysicalDeviceExternalSemaphorePropertiesKHR(physicalDevice, pExternalSemaphoreInfo, pExternalSemaphoreProperties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetPhysicalDeviceExternalSemaphorePropertiesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetPhysicalDeviceExternalSemaphorePropertiesKHR), physicalDevice, pExternalSemaphoreInfo, pExternalSemaphoreProperties)
}
