// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_create_renderpass2
//

// Package mock_create_renderpass2 is a generated GoMock package.
package mock_create_renderpass2

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_create_renderpass2 "github.com/vkngwrapper/extensions/v3/khr_create_renderpass2"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// CmdBeginRenderPass2 mocks base method.
func (m *MockExtensionDriver) CmdBeginRenderPass2(commandBuffer core1_0.CommandBuffer, renderPassBegin core1_0.RenderPassBeginInfo, subpassBegin khr_create_renderpass2.SubpassBeginInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdBeginRenderPass2", commandBuffer, renderPassBegin, subpassBegin)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdBeginRenderPass2 indicates an expected call of CmdBeginRenderPass2.
func (mr *MockExtensionDriverMockRecorder) CmdBeginRenderPass2(commandBuffer, renderPassBegin, subpassBegin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdBeginRenderPass2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdBeginRenderPass2), commandBuffer, renderPassBegin, subpassBegin)
}

// CmdEndRenderPass2 mocks base method.
func (m *MockExtensionDriver) CmdEndRenderPass2(commandBuffer core1_0.CommandBuffer, subpassEnd khr_create_renderpass2.SubpassEndInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdEndRenderPass2", commandBuffer, subpassEnd)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdEndRenderPass2 indicates an expected call of CmdEndRenderPass2.
func (mr *MockExtensionDriverMockRecorder) CmdEndRenderPass2(commandBuffer, subpassEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdEndRenderPass2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdEndRenderPass2), commandBuffer, subpassEnd)
}

// CmdNextSubpass2 mocks base method.
func (m *MockExtensionDriver) CmdNextSubpass2(commandBuffer core1_0.CommandBuffer, subpassBegin khr_create_renderpass2.SubpassBeginInfo, subpassEnd khr_create_renderpass2.SubpassEndInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdNextSubpass2", commandBuffer, subpassBegin, subpassEnd)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdNextSubpass2 indicates an expected call of CmdNextSubpass2.
func (mr *MockExtensionDriverMockRecorder) CmdNextSubpass2(commandBuffer, subpassBegin, subpassEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdNextSubpass2", reflect.TypeOf((*MockExtensionDriver)(nil).CmdNextSubpass2), commandBuffer, subpassBegin, subpassEnd)
}

// CreateRenderPass2 mocks base method.
func (m *MockExtensionDriver) CreateRenderPass2(allocator *loader.AllocationCallbacks, options khr_create_renderpass2.RenderPassCreateInfo2) (core1_0.RenderPass, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRenderPass2", allocator, options)
	ret0, _ := ret[0].(core1_0.RenderPass)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRenderPass2 indicates an expected call of CreateRenderPass2.
func (mr *MockExtensionDriverMockRecorder) CreateRenderPass2(allocator, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRenderPass2", reflect.TypeOf((*MockExtensionDriver)(nil).CreateRenderPass2), allocator, options)
}
