// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_create_renderpass2
//

// Package mock_create_renderpass2 is a generated GoMock package.
package mock_create_renderpass2

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_create_renderpass2_loader "github.com/vkngwrapper/extensions/v3/khr_create_renderpass2/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkCmdBeginRenderPass2KHR mocks base method.
func (m *MockLoader) VkCmdBeginRenderPass2KHR(commandBuffer loader.VkCommandBuffer, pRenderPassBegin *loader.VkRenderPassBeginInfo, pSubpassBeginInfo *khr_create_renderpass2_loader.VkSubpassBeginInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdBeginRenderPass2KHR", commandBuffer, pRenderPassBegin, pSubpassBeginInfo)
}

// VkCmdBeginRenderPass2KHR indicates an expected call of VkCmdBeginRenderPass2KHR.
func (mr *MockLoaderMockRecorder) VkCmdBeginRenderPass2KHR(commandBuffer, pRenderPassBegin, pSubpassBeginInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdBeginRenderPass2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdBeginRenderPass2KHR), commandBuffer, pRenderPassBegin, pSubpassBeginInfo)
}

// VkCmdEndRenderPass2KHR mocks base method.
func (m *MockLoader) VkCmdEndRenderPass2KHR(commandBuffer loader.VkCommandBuffer, pSubpassEndInfo *khr_create_renderpass2_loader.VkSubpassEndInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdEndRenderPass2KHR", commandBuffer, pSubpassEndInfo)
}

// VkCmdEndRenderPass2KHR indicates an expected call of VkCmdEndRenderPass2KHR.
func (mr *MockLoaderMockRecorder) VkCmdEndRenderPass2KHR(commandBuffer, pSubpassEndInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdEndRenderPass2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdEndRenderPass2KHR), commandBuffer, pSubpassEndInfo)
}

// VkCmdNextSubpass2KHR mocks base method.
func (m *MockLoader) VkCmdNextSubpass2KHR(commandBuffer loader.VkCommandBuffer, pSubpassBeginInfo *khr_create_renderpass2_loader.VkSubpassBeginInfoKHR, pSubpassEndInfo *khr_create_renderpass2_loader.VkSubpassEndInfoKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdNextSubpass2KHR", commandBuffer, pSubpassBeginInfo, pSubpassEndInfo)
}

// VkCmdNextSubpass2KHR indicates an expected call of VkCmdNextSubpass2KHR.
func (mr *MockLoaderMockRecorder) VkCmdNextSubpass2KHR(commandBuffer, pSubpassBeginInfo, pSubpassEndInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdNextSubpass2KHR", reflect.TypeOf((*MockLoader)(nil).VkCmdNextSubpass2KHR), commandBuffer, pSubpassBeginInfo, pSubpassEndInfo)
}

// VkCreateRenderPass2KHR mocks base method.
func (m *MockLoader) VkCreateRenderPass2KHR(device loader.VkDevice, pCreateInfo *khr_create_renderpass2_loader.VkRenderPassCreateInfo2KHR, pAllocator *loader.VkAllocationCallbacks, pRenderPass *loader.VkRenderPass) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCreateRenderPass2KHR", device, pCreateInfo, pAllocator, pRenderPass)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCreateRenderPass2KHR indicates an expected call of VkCreateRenderPass2KHR.
func (mr *MockLoaderMockRecorder) VkCreateRenderPass2KHR(device, pCreateInfo, pAllocator, pRenderPass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCreateRenderPass2KHR", reflect.TypeOf((*MockLoader)(nil).VkCreateRenderPass2KHR), device, pCreateInfo, pAllocator, pRenderPass)
}
