// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_full_screen_exclusive
//

// Package mock_full_screen_exclusive is a generated GoMock package.
package mock_full_screen_exclusive

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_device_group "github.com/vkngwrapper/extensions/v3/khr_device_group"
	khr_get_surface_capabilities2 "github.com/vkngwrapper/extensions/v3/khr_get_surface_capabilities2"
	khr_surface "github.com/vkngwrapper/extensions/v3/khr_surface"
	khr_swapchain "github.com/vkngwrapper/extensions/v3/khr_swapchain"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// AcquireFullScreenExclusiveMode mocks base method.
func (m *MockExtensionDriver) AcquireFullScreenExclusiveMode(swapchain khr_swapchain.Swapchain) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireFullScreenExclusiveMode", swapchain)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireFullScreenExclusiveMode indicates an expected call of AcquireFullScreenExclusiveMode.
func (mr *MockExtensionDriverMockRecorder) AcquireFullScreenExclusiveMode(swapchain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireFullScreenExclusiveMode", reflect.TypeOf((*MockExtensionDriver)(nil).AcquireFullScreenExclusiveMode), swapchain)
}

// GetPhysicalDeviceSurfacePresentModes2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceSurfacePresentModes2(physicalDevice core1_0.PhysicalDevice, o khr_get_surface_capabilities2.PhysicalDeviceSurfaceInfo2) ([]khr_surface.PresentMode, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceSurfacePresentModes2", physicalDevice, o)
	ret0, _ := ret[0].([]khr_surface.PresentMode)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPhysicalDeviceSurfacePresentModes2 indicates an expected call of GetPhysicalDeviceSurfacePresentModes2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceSurfacePresentModes2(physicalDevice, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceSurfacePresentModes2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceSurfacePresentModes2), physicalDevice, o)
}

// ReleaseFullScreenExclusiveMode mocks base method.
func (m *MockExtensionDriver) ReleaseFullScreenExclusiveMode(swapchain khr_swapchain.Swapchain) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseFullScreenExclusiveMode", swapchain)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseFullScreenExclusiveMode indicates an expected call of ReleaseFullScreenExclusiveMode.
func (mr *MockExtensionDriverMockRecorder) ReleaseFullScreenExclusiveMode(swapchain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseFullScreenExclusiveMode", reflect.TypeOf((*MockExtensionDriver)(nil).ReleaseFullScreenExclusiveMode), swapchain)
}

// MockExtensionDriverWithDeviceGroups is a mock of ExtensionDriverWithDeviceGroups interface.
type MockExtensionDriverWithDeviceGroups struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverWithDeviceGroupsMockRecorder
	isgomock struct{}
}

// MockExtensionDriverWithDeviceGroupsMockRecorder is the mock recorder for MockExtensionDriverWithDeviceGroups.
type MockExtensionDriverWithDeviceGroupsMockRecorder struct {
	mock *MockExtensionDriverWithDeviceGroups
}

// NewMockExtensionDriverWithDeviceGroups creates a new mock instance.
func NewMockExtensionDriverWithDeviceGroups(ctrl *gomock.Controller) *MockExtensionDriverWithDeviceGroups {
	mock := &MockExtensionDriverWithDeviceGroups{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverWithDeviceGroupsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriverWithDeviceGroups) EXPECT() *MockExtensionDriverWithDeviceGroupsMockRecorder {
	return m.recorder
}

// GetDeviceGroupSurfacePresentModes2 mocks base method.
func (m *MockExtensionDriverWithDeviceGroups) GetDeviceGroupSurfacePresentModes2(o khr_get_surface_capabilities2.PhysicalDeviceSurfaceInfo2, out *khr_device_group.DeviceGroupPresentModeFlags) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceGroupSurfacePresentModes2", o, out)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceGroupSurfacePresentModes2 indicates an expected call of GetDeviceGroupSurfacePresentModes2.
func (mr *MockExtensionDriverWithDeviceGroupsMockRecorder) GetDeviceGroupSurfacePresentModes2(o, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceGroupSurfacePresentModes2", reflect.TypeOf((*MockExtensionDriverWithDeviceGroups)(nil).GetDeviceGroupSurfacePresentModes2), o, out)
}
