// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_full_screen_exclusive
//

// Package mock_full_screen_exclusive is a generated GoMock package.
package mock_full_screen_exclusive

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_device_group_loader "github.com/vkngwrapper/extensions/v3/khr_device_group/loader"
	khr_get_surface_capabilities2_loader "github.com/vkngwrapper/extensions/v3/khr_get_surface_capabilities2/loader"
	khr_surface_loader "github.com/vkngwrapper/extensions/v3/khr_surface/loader"
	khr_swapchain_loader "github.com/vkngwrapper/extensions/v3/khr_swapchain/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkAcquireFullScreenExclusiveModeEXT mocks base method.
func (m *MockLoader) VkAcquireFullScreenExclusiveModeEXT(device loader.VkDevice, swapchain khr_swapchain_loader.VkSwapchainKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkAcquireFullScreenExclusiveModeEXT", device, swapchain)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkAcquireFullScreenExclusiveModeEXT indicates an expected call of VkAcquireFullScreenExclusiveModeEXT.
func (mr *MockLoaderMockRecorder) VkAcquireFullScreenExclusiveModeEXT(device, swapchain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkAcquireFullScreenExclusiveModeEXT", reflect.TypeOf((*MockLoader)(nil).VkAcquireFullScreenExclusiveModeEXT), device, swapchain)
}

// VkGetDeviceGroupSurfacePresentModes2EXT mocks base method.
func (m *MockLoader) VkGetDeviceGroupSurfacePresentModes2EXT(device loader.VkDevice, pSurfaceInfo *khr_get_surface_capabilities2_loader.VkPhysicalDeviceSurfaceInfo2KHR, pModes *khr_device_group_loader.VkDeviceGroupPresentModeFlagsKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeviceGroupSurfacePresentModes2EXT", device, pSurfaceInfo, pModes)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetDeviceGroupSurfacePresentModes2EXT indicates an expected call of VkGetDeviceGroupSurfacePresentModes2EXT.
func (mr *MockLoaderMockRecorder) VkGetDeviceGroupSurfacePresentModes2EXT(device, pSurfaceInfo, pModes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceGroupSurfacePresentModes2EXT", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceGroupSurfacePresentModes2EXT), device, pSurfaceInfo, pModes)
}

// VkGetPhysicalDeviceSurfacePresentModes2EXT mocks base method.
func (m *MockLoader) VkGetPhysicalDeviceSurfacePresentModes2EXT(physicalDevice loader.VkPhysicalDevice, pSurfaceInfo *khr_get_surface_capabilities2_loader.VkPhysicalDeviceSurfaceInfo2KHR, pPresentModeCount *loader.Uint32, pPresentModes *khr_surface_loader.VkPresentModeKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetPhysicalDeviceSurfacePresentModes2EXT", physicalDevice, pSurfaceInfo, pPresentModeCount, pPresentModes)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetPhysicalDeviceSurfacePresentModes2EXT indicates an expected call of VkGetPhysicalDeviceSurfacePresentModes2EXT.
func (mr *MockLoaderMockRecorder) VkGetPhysicalDeviceSurfacePresentModes2EXT(physicalDevice, pSurfaceInfo, pPresentModeCount, pPresentModes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetPhysicalDeviceSurfacePresentModes2EXT", reflect.TypeOf((*MockLoader)(nil).VkGetPhysicalDeviceSurfacePresentModes2EXT), physicalDevice, pSurfaceInfo, pPresentModeCount, pPresentModes)
}

// VkReleaseFullScreenExclusiveModeEXT mocks base method.
func (m *MockLoader) VkReleaseFullScreenExclusiveModeEXT(device loader.VkDevice, swapchain khr_swapchain_loader.VkSwapchainKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkReleaseFullScreenExclusiveModeEXT", device, swapchain)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkReleaseFullScreenExclusiveModeEXT indicates an expected call of VkReleaseFullScreenExclusiveModeEXT.
func (mr *MockLoaderMockRecorder) VkReleaseFullScreenExclusiveModeEXT(device, swapchain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkReleaseFullScreenExclusiveModeEXT", reflect.TypeOf((*MockLoader)(nil).VkReleaseFullScreenExclusiveModeEXT), device, swapchain)
}
