// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_get_surface_capabilities2
//

// Package mock_get_surface_capabilities2 is a generated GoMock package.
package mock_get_surface_capabilities2

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_get_surface_capabilities2 "github.com/vkngwrapper/extensions/v3/khr_get_surface_capabilities2"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// GetPhysicalDeviceSurfaceCapabilities2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceSurfaceCapabilities2(physicalDevice core1_0.PhysicalDevice, o khr_get_surface_capabilities2.PhysicalDeviceSurfaceInfo2, out *khr_get_surface_capabilities2.SurfaceCapabilities2) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceSurfaceCapabilities2", physicalDevice, o, out)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhysicalDeviceSurfaceCapabilities2 indicates an expected call of GetPhysicalDeviceSurfaceCapabilities2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceSurfaceCapabilities2(physicalDevice, o, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceSurfaceCapabilities2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceSurfaceCapabilities2), physicalDevice, o, out)
}

// GetPhysicalDeviceSurfaceFormats2 mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceSurfaceFormats2(physicalDevice core1_0.PhysicalDevice, o khr_get_surface_capabilities2.PhysicalDeviceSurfaceInfo2, outDataFactory func() *khr_get_surface_capabilities2.SurfaceFormat2) ([]*khr_get_surface_capabilities2.SurfaceFormat2, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceSurfaceFormats2", physicalDevice, o, outDataFactory)
	ret0, _ := ret[0].([]*khr_get_surface_capabilities2.SurfaceFormat2)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPhysicalDeviceSurfaceFormats2 indicates an expected call of GetPhysicalDeviceSurfaceFormats2.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceSurfaceFormats2(physicalDevice, o, outDataFactory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceSurfaceFormats2", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceSurfaceFormats2), physicalDevice, o, outDataFactory)
}
