// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_get_surface_capabilities2
//

// Package mock_get_surface_capabilities2 is a generated GoMock package.
package mock_get_surface_capabilities2

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_get_surface_capabilities2_loader "github.com/vkngwrapper/extensions/v3/khr_get_surface_capabilities2/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkGetPhysicalDeviceSurfaceCapabilities2KHR mocks base method.
func (m *MockLoader) VkGetPhysicalDeviceSurfaceCapabilities2KHR(physicalDevice loader.VkPhysicalDevice, pSurfaceInfo *khr_get_surface_capabilities2_loader.VkPhysicalDeviceSurfaceInfo2KHR, pSurfaceCapabilities *khr_get_surface_capabilities2_loader.VkSurfaceCapabilities2KHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetPhysicalDeviceSurfaceCapabilities2KHR", physicalDevice, pSurfaceInfo, pSurfaceCapabilities)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetPhysicalDeviceSurfaceCapabilities2KHR indicates an expected call of VkGetPhysicalDeviceSurfaceCapabilities2KHR.
func (mr *MockLoaderMockRecorder) VkGetPhysicalDeviceSurfaceCapabilities2KHR(physicalDevice, pSurfaceInfo, pSurfaceCapabilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetPhysicalDeviceSurfaceCapabilities2KHR", reflect.TypeOf((*MockLoader)(nil).VkGetPhysicalDeviceSurfaceCapabilities2KHR), physicalDevice, pSurfaceInfo, pSurfaceCapabilities)
}

// VkGetPhysicalDeviceSurfaceFormats2KHR mocks base method.
func (m *MockLoader) VkGetPhysicalDeviceSurfaceFormats2KHR(physicalDevice loader.VkPhysicalDevice, pSurfaceInfo *khr_get_surface_capabilities2_loader.VkPhysicalDeviceSurfaceInfo2KHR, pSurfaceFormatCount *loader.Uint32, pSurfaceFormats *khr_get_surface_capabilities2_loader.VkSurfaceFormat2KHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetPhysicalDeviceSurfaceFormats2KHR", physicalDevice, pSurfaceInfo, pSurfaceFormatCount, pSurfaceFormats)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetPhysicalDeviceSurfaceFormats2KHR indicates an expected call of VkGetPhysicalDeviceSurfaceFormats2KHR.
func (mr *MockLoaderMockRecorder) VkGetPhysicalDeviceSurfaceFormats2KHR(physicalDevice, pSurfaceInfo, pSurfaceFormatCount, pSurfaceFormats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetPhysicalDeviceSurfaceFormats2KHR", reflect.TypeOf((*MockLoader)(nil).VkGetPhysicalDeviceSurfaceFormats2KHR), physicalDevice, pSurfaceInfo, pSurfaceFormatCount, pSurfaceFormats)
}
