// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ../mocks/extension1_1.go -package mock_swapchain -mock_names Extension=MockExtension1_1
//

// Package mock_swapchain is a generated GoMock package.
package mock_swapchain

import (
	reflect "reflect"

	core "github.com/vkngwrapper/core/v3"
	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_surface "github.com/vkngwrapper/extensions/v3/khr_surface"
	khr_swapchain1_1 "github.com/vkngwrapper/extensions/v3/khr_swapchain/khr_swapchain1_1"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// AcquireNextImage2 mocks base method.
func (m *MockExtensionDriver) AcquireNextImage2(o khr_swapchain1_1.AcquireNextImageInfo) (int, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireNextImage2", o)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcquireNextImage2 indicates an expected call of AcquireNextImage2.
func (mr *MockExtensionDriverMockRecorder) AcquireNextImage2(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireNextImage2", reflect.TypeOf((*MockExtensionDriver)(nil).AcquireNextImage2), o)
}

// DeviceGroupSurfacePresentModeFlags mocks base method.
func (m *MockExtensionDriver) DeviceGroupSurfacePresentModeFlags(surface khr_surface.Surface) (khr_swapchain1_1.DeviceGroupPresentModeFlags, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceGroupSurfacePresentModeFlags", surface)
	ret0, _ := ret[0].(khr_swapchain1_1.DeviceGroupPresentModeFlags)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeviceGroupSurfacePresentModeFlags indicates an expected call of DeviceGroupSurfacePresentModeFlags.
func (mr *MockExtensionDriverMockRecorder) DeviceGroupSurfacePresentModeFlags(surface any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceGroupSurfacePresentModeFlags", reflect.TypeOf((*MockExtensionDriver)(nil).DeviceGroupSurfacePresentModeFlags), surface)
}

// GetDeviceGroupPresentCapabilities mocks base method.
func (m *MockExtensionDriver) GetDeviceGroupPresentCapabilities(outData *khr_swapchain1_1.DeviceGroupPresentCapabilities) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceGroupPresentCapabilities", outData)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceGroupPresentCapabilities indicates an expected call of GetDeviceGroupPresentCapabilities.
func (mr *MockExtensionDriverMockRecorder) GetDeviceGroupPresentCapabilities(outData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceGroupPresentCapabilities", reflect.TypeOf((*MockExtensionDriver)(nil).GetDeviceGroupPresentCapabilities), outData)
}

// GetPhysicalDevicePresentRectangles mocks base method.
func (m *MockExtensionDriver) GetPhysicalDevicePresentRectangles(physicalDevice core.PhysicalDevice, surface khr_surface.Surface) ([]core1_0.Rect2D, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDevicePresentRectangles", physicalDevice, surface)
	ret0, _ := ret[0].([]core1_0.Rect2D)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPhysicalDevicePresentRectangles indicates an expected call of GetPhysicalDevicePresentRectangles.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDevicePresentRectangles(physicalDevice, surface any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDevicePresentRectangles", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDevicePresentRectangles), physicalDevice, surface)
}
