// Code generated by MockGen. DO NOT EDIT.
// Source: extension.go
//
// Generated by this command:
//
//	mockgen -source extension.go -destination ./mocks/extension.go -package mock_swapchain
//

// Package mock_swapchain is a generated GoMock package.
package mock_swapchain
