// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_swapchain
//

// Package mock_swapchain is a generated GoMock package.
package mock_swapchain

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_surface_loader "github.com/vkngwrapper/extensions/v3/khr_surface/loader"
	khr_swapchain_loader "github.com/vkngwrapper/extensions/v3/khr_swapchain/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkAcquireNextImage2KHR mocks base method.
func (m *MockLoader) VkAcquireNextImage2KHR(device loader.VkDevice, pAcquireInfo *khr_swapchain_loader.VkAcquireNextImageInfoKHR, pImageIndex *loader.Uint32) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkAcquireNextImage2KHR", device, pAcquireInfo, pImageIndex)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkAcquireNextImage2KHR indicates an expected call of VkAcquireNextImage2KHR.
func (mr *MockLoaderMockRecorder) VkAcquireNextImage2KHR(device, pAcquireInfo, pImageIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkAcquireNextImage2KHR", reflect.TypeOf((*MockLoader)(nil).VkAcquireNextImage2KHR), device, pAcquireInfo, pImageIndex)
}

// VkAcquireNextImageKHR mocks base method.
func (m *MockLoader) VkAcquireNextImageKHR(device loader.VkDevice, swapchain khr_swapchain_loader.VkSwapchainKHR, timeout loader.Uint64, semaphore loader.VkSemaphore, fence loader.VkFence, pImageIndex *loader.Uint32) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkAcquireNextImageKHR", device, swapchain, timeout, semaphore, fence, pImageIndex)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkAcquireNextImageKHR indicates an expected call of VkAcquireNextImageKHR.
func (mr *MockLoaderMockRecorder) VkAcquireNextImageKHR(device, swapchain, timeout, semaphore, fence, pImageIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkAcquireNextImageKHR", reflect.TypeOf((*MockLoader)(nil).VkAcquireNextImageKHR), device, swapchain, timeout, semaphore, fence, pImageIndex)
}

// VkCreateSwapchainKHR mocks base method.
func (m *MockLoader) VkCreateSwapchainKHR(device loader.VkDevice, pCreateInfo *khr_swapchain_loader.VkSwapchainCreateInfoKHR, pAllocator *loader.VkAllocationCallbacks, pSwapchain *khr_swapchain_loader.VkSwapchainKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCreateSwapchainKHR", device, pCreateInfo, pAllocator, pSwapchain)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCreateSwapchainKHR indicates an expected call of VkCreateSwapchainKHR.
func (mr *MockLoaderMockRecorder) VkCreateSwapchainKHR(device, pCreateInfo, pAllocator, pSwapchain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCreateSwapchainKHR", reflect.TypeOf((*MockLoader)(nil).VkCreateSwapchainKHR), device, pCreateInfo, pAllocator, pSwapchain)
}

// VkDestroySwapchainKHR mocks base method.
func (m *MockLoader) VkDestroySwapchainKHR(device loader.VkDevice, swapchain khr_swapchain_loader.VkSwapchainKHR, pAllocator *loader.VkAllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkDestroySwapchainKHR", device, swapchain, pAllocator)
}

// VkDestroySwapchainKHR indicates an expected call of VkDestroySwapchainKHR.
func (mr *MockLoaderMockRecorder) VkDestroySwapchainKHR(device, swapchain, pAllocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkDestroySwapchainKHR", reflect.TypeOf((*MockLoader)(nil).VkDestroySwapchainKHR), device, swapchain, pAllocator)
}

// VkGetDeviceGroupPresentCapabilitiesKHR mocks base method.
func (m *MockLoader) VkGetDeviceGroupPresentCapabilitiesKHR(device loader.VkDevice, pDeviceGroupPresentCapabilities *khr_swapchain_loader.VkDeviceGroupPresentCapabilitiesKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeviceGroupPresentCapabilitiesKHR", device, pDeviceGroupPresentCapabilities)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetDeviceGroupPresentCapabilitiesKHR indicates an expected call of VkGetDeviceGroupPresentCapabilitiesKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceGroupPresentCapabilitiesKHR(device, pDeviceGroupPresentCapabilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceGroupPresentCapabilitiesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceGroupPresentCapabilitiesKHR), device, pDeviceGroupPresentCapabilities)
}

// VkGetDeviceGroupSurfacePresentModesKHR mocks base method.
func (m *MockLoader) VkGetDeviceGroupSurfacePresentModesKHR(device loader.VkDevice, surface khr_surface_loader.VkSurfaceKHR, pModes *khr_swapchain_loader.VkDeviceGroupPresentModeFlagsKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetDeviceGroupSurfacePresentModesKHR", device, surface, pModes)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetDeviceGroupSurfacePresentModesKHR indicates an expected call of VkGetDeviceGroupSurfacePresentModesKHR.
func (mr *MockLoaderMockRecorder) VkGetDeviceGroupSurfacePresentModesKHR(device, surface, pModes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDeviceGroupSurfacePresentModesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDeviceGroupSurfacePresentModesKHR), device, surface, pModes)
}

// VkGetPhysicalDevicePresentRectanglesKHR mocks base method.
func (m *MockLoader) VkGetPhysicalDevicePresentRectanglesKHR(physicalDevice loader.VkPhysicalDevice, surface khr_surface_loader.VkSurfaceKHR, pRectCount *loader.Uint32, pRects *loader.VkRect2D) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetPhysicalDevicePresentRectanglesKHR", physicalDevice, surface, pRectCount, pRects)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetPhysicalDevicePresentRectanglesKHR indicates an expected call of VkGetPhysicalDevicePresentRectanglesKHR.
func (mr *MockLoaderMockRecorder) VkGetPhysicalDevicePresentRectanglesKHR(physicalDevice, surface, pRectCount, pRects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetPhysicalDevicePresentRectanglesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetPhysicalDevicePresentRectanglesKHR), physicalDevice, surface, pRectCount, pRects)
}

// VkGetSwapchainImagesKHR mocks base method.
func (m *MockLoader) VkGetSwapchainImagesKHR(device loader.VkDevice, swapchain khr_swapchain_loader.VkSwapchainKHR, pSwapchainImageCount *loader.Uint32, pSwapchainImages *loader.VkImage) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkGetSwapchainImagesKHR", device, swapchain, pSwapchainImageCount, pSwapchainImages)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkGetSwapchainImagesKHR indicates an expected call of VkGetSwapchainImagesKHR.
func (mr *MockLoaderMockRecorder) VkGetSwapchainImagesKHR(device, swapchain, pSwapchainImageCount, pSwapchainImages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetSwapchainImagesKHR", reflect.TypeOf((*MockLoader)(nil).VkGetSwapchainImagesKHR), device, swapchain, pSwapchainImageCount, pSwapchainImages)
}

// VkQueuePresentKHR mocks base method.
func (m *MockLoader) VkQueuePresentKHR(queue loader.VkQueue, pPresentInfo *khr_swapchain_loader.VkPresentInfoKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkQueuePresentKHR", queue, pPresentInfo)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkQueuePresentKHR indicates an expected call of VkQueuePresentKHR.
func (mr *MockLoaderMockRecorder) VkQueuePresentKHR(queue, pPresentInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkQueuePresentKHR", reflect.TypeOf((*MockLoader)(nil).VkQueuePresentKHR), queue, pPresentInfo)
}
