// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_maintenance3
//

// Package mock_maintenance3 is a generated GoMock package.
package mock_maintenance3

import (
	reflect "reflect"

	core "github.com/vkngwrapper/core/v3"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	khr_maintenance3 "github.com/vkngwrapper/extensions/v3/khr_maintenance3"
	gomock "go.uber.org/mock/gomock"
)

// MockExtension is a mock of Extension interface.
type MockExtension struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionMockRecorder
	isgomock struct{}
}

// MockExtensionMockRecorder is the mock recorder for MockExtension.
type MockExtensionMockRecorder struct {
	mock *MockExtension
}

// NewMockExtension creates a new mock instance.
func NewMockExtension(ctrl *gomock.Controller) *MockExtension {
	mock := &MockExtension{ctrl: ctrl}
	mock.recorder = &MockExtensionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtension) EXPECT() *MockExtensionMockRecorder {
	return m.recorder
}

// DescriptorSetLayoutSupport mocks base method.
func (m *MockExtension) DescriptorSetLayoutSupport(device core.Device, setLayoutOptions core1_0.DescriptorSetLayoutCreateInfo, outData *khr_maintenance3.DescriptorSetLayoutSupport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescriptorSetLayoutSupport", device, setLayoutOptions, outData)
	ret0, _ := ret[0].(error)
	return ret0
}

// DescriptorSetLayoutSupport indicates an expected call of DescriptorSetLayoutSupport.
func (mr *MockExtensionMockRecorder) DescriptorSetLayoutSupport(device, setLayoutOptions, outData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescriptorSetLayoutSupport", reflect.TypeOf((*MockExtension)(nil).DescriptorSetLayoutSupport), device, setLayoutOptions, outData)
}
