// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_maintenance3
//

// Package mock_maintenance3 is a generated GoMock package.
package mock_maintenance3

import (
	reflect "reflect"

	loader "github.com/vkngwrapper/core/v3/loader"
	khr_maintenance3_loader "github.com/vkngwrapper/extensions/v3/khr_maintenance3/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkGetDescriptorSetLayoutSupportKHR mocks base method.
func (m *MockLoader) VkGetDescriptorSetLayoutSupportKHR(device loader.VkDevice, pCreateInfo *loader.VkDescriptorSetLayoutCreateInfo, pSupport *khr_maintenance3_loader.VkDescriptorSetLayoutSupportKHR) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkGetDescriptorSetLayoutSupportKHR", device, pCreateInfo, pSupport)
}

// VkGetDescriptorSetLayoutSupportKHR indicates an expected call of VkGetDescriptorSetLayoutSupportKHR.
func (mr *MockLoaderMockRecorder) VkGetDescriptorSetLayoutSupportKHR(device, pCreateInfo, pSupport any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkGetDescriptorSetLayoutSupportKHR", reflect.TypeOf((*MockLoader)(nil).VkGetDescriptorSetLayoutSupportKHR), device, pCreateInfo, pSupport)
}
