// Code generated by MockGen. DO NOT EDIT.
// Source: iface.go
//
// Generated by this command:
//
//	mockgen -source iface.go -destination ./mocks/extension.go -package mock_descriptor_update_template
//

// Package mock_descriptor_update_template is a generated GoMock package.
package mock_descriptor_update_template

import (
	reflect "reflect"

	core "github.com/vkngwrapper/core/v3"
	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_descriptor_update_template "github.com/vkngwrapper/extensions/v3/khr_descriptor_update_template"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// CreateDescriptorUpdateTemplate mocks base method.
func (m *MockExtensionDriver) CreateDescriptorUpdateTemplate(o khr_descriptor_update_template.DescriptorUpdateTemplateCreateInfo, allocator *loader.AllocationCallbacks) (core.DescriptorUpdateTemplate, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDescriptorUpdateTemplate", o, allocator)
	ret0, _ := ret[0].(core.DescriptorUpdateTemplate)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateDescriptorUpdateTemplate indicates an expected call of CreateDescriptorUpdateTemplate.
func (mr *MockExtensionDriverMockRecorder) CreateDescriptorUpdateTemplate(o, allocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDescriptorUpdateTemplate", reflect.TypeOf((*MockExtensionDriver)(nil).CreateDescriptorUpdateTemplate), o, allocator)
}

// DestroyDescriptorUpdateTemplate mocks base method.
func (m *MockExtensionDriver) DestroyDescriptorUpdateTemplate(template core.DescriptorUpdateTemplate, allocator *loader.AllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DestroyDescriptorUpdateTemplate", template, allocator)
}

// DestroyDescriptorUpdateTemplate indicates an expected call of DestroyDescriptorUpdateTemplate.
func (mr *MockExtensionDriverMockRecorder) DestroyDescriptorUpdateTemplate(template, allocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyDescriptorUpdateTemplate", reflect.TypeOf((*MockExtensionDriver)(nil).DestroyDescriptorUpdateTemplate), template, allocator)
}

// UpdateDescriptorSetWithTemplateFromBuffer mocks base method.
func (m *MockExtensionDriver) UpdateDescriptorSetWithTemplateFromBuffer(descriptorSet core.DescriptorSet, template core.DescriptorUpdateTemplate, data core1_0.DescriptorBufferInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDescriptorSetWithTemplateFromBuffer", descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromBuffer indicates an expected call of UpdateDescriptorSetWithTemplateFromBuffer.
func (mr *MockExtensionDriverMockRecorder) UpdateDescriptorSetWithTemplateFromBuffer(descriptorSet, template, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDescriptorSetWithTemplateFromBuffer", reflect.TypeOf((*MockExtensionDriver)(nil).UpdateDescriptorSetWithTemplateFromBuffer), descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromImage mocks base method.
func (m *MockExtensionDriver) UpdateDescriptorSetWithTemplateFromImage(descriptorSet core.DescriptorSet, template core.DescriptorUpdateTemplate, data core1_0.DescriptorImageInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDescriptorSetWithTemplateFromImage", descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromImage indicates an expected call of UpdateDescriptorSetWithTemplateFromImage.
func (mr *MockExtensionDriverMockRecorder) UpdateDescriptorSetWithTemplateFromImage(descriptorSet, template, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDescriptorSetWithTemplateFromImage", reflect.TypeOf((*MockExtensionDriver)(nil).UpdateDescriptorSetWithTemplateFromImage), descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromObjectHandle mocks base method.
func (m *MockExtensionDriver) UpdateDescriptorSetWithTemplateFromObjectHandle(descriptorSet core.DescriptorSet, template core.DescriptorUpdateTemplate, data loader.VulkanHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDescriptorSetWithTemplateFromObjectHandle", descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromObjectHandle indicates an expected call of UpdateDescriptorSetWithTemplateFromObjectHandle.
func (mr *MockExtensionDriverMockRecorder) UpdateDescriptorSetWithTemplateFromObjectHandle(descriptorSet, template, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDescriptorSetWithTemplateFromObjectHandle", reflect.TypeOf((*MockExtensionDriver)(nil).UpdateDescriptorSetWithTemplateFromObjectHandle), descriptorSet, template, data)
}
