// Code generated by MockGen. DO NOT EDIT.
// Source: iface.go
//
// Generated by this command:
//
//	mockgen -source iface.go -destination ./mocks/extension.go -package mock_descriptor_update_template
//

// Package mock_descriptor_update_template is a generated GoMock package.
package mock_descriptor_update_template

import (
	reflect "reflect"

	core "github.com/vkngwrapper/core/v3"
	common "github.com/vkngwrapper/core/v3/common"
	core1_0 "github.com/vkngwrapper/core/v3/core1_0"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_descriptor_update_template "github.com/vkngwrapper/extensions/v3/khr_descriptor_update_template"
	gomock "go.uber.org/mock/gomock"
)

// MockExtension is a mock of Extension interface.
type MockExtension struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionMockRecorder
	isgomock struct{}
}

// MockExtensionMockRecorder is the mock recorder for MockExtension.
type MockExtensionMockRecorder struct {
	mock *MockExtension
}

// NewMockExtension creates a new mock instance.
func NewMockExtension(ctrl *gomock.Controller) *MockExtension {
	mock := &MockExtension{ctrl: ctrl}
	mock.recorder = &MockExtensionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtension) EXPECT() *MockExtensionMockRecorder {
	return m.recorder
}

// CreateDescriptorUpdateTemplate mocks base method.
func (m *MockExtension) CreateDescriptorUpdateTemplate(device core.Device, o khr_descriptor_update_template.DescriptorUpdateTemplateCreateInfo, allocator *loader.AllocationCallbacks) (core.DescriptorUpdateTemplate, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDescriptorUpdateTemplate", device, o, allocator)
	ret0, _ := ret[0].(core.DescriptorUpdateTemplate)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateDescriptorUpdateTemplate indicates an expected call of CreateDescriptorUpdateTemplate.
func (mr *MockExtensionMockRecorder) CreateDescriptorUpdateTemplate(device, o, allocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDescriptorUpdateTemplate", reflect.TypeOf((*MockExtension)(nil).CreateDescriptorUpdateTemplate), device, o, allocator)
}

// DestroyDescriptorUpdateTemplate mocks base method.
func (m *MockExtension) DestroyDescriptorUpdateTemplate(template core.DescriptorUpdateTemplate, allocator *loader.AllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DestroyDescriptorUpdateTemplate", template, allocator)
}

// DestroyDescriptorUpdateTemplate indicates an expected call of DestroyDescriptorUpdateTemplate.
func (mr *MockExtensionMockRecorder) DestroyDescriptorUpdateTemplate(template, allocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyDescriptorUpdateTemplate", reflect.TypeOf((*MockExtension)(nil).DestroyDescriptorUpdateTemplate), template, allocator)
}

// UpdateDescriptorSetWithTemplateFromBuffer mocks base method.
func (m *MockExtension) UpdateDescriptorSetWithTemplateFromBuffer(descriptorSet core.DescriptorSet, template core.DescriptorUpdateTemplate, data core1_0.DescriptorBufferInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDescriptorSetWithTemplateFromBuffer", descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromBuffer indicates an expected call of UpdateDescriptorSetWithTemplateFromBuffer.
func (mr *MockExtensionMockRecorder) UpdateDescriptorSetWithTemplateFromBuffer(descriptorSet, template, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDescriptorSetWithTemplateFromBuffer", reflect.TypeOf((*MockExtension)(nil).UpdateDescriptorSetWithTemplateFromBuffer), descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromImage mocks base method.
func (m *MockExtension) UpdateDescriptorSetWithTemplateFromImage(descriptorSet core.DescriptorSet, template core.DescriptorUpdateTemplate, data core1_0.DescriptorImageInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDescriptorSetWithTemplateFromImage", descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromImage indicates an expected call of UpdateDescriptorSetWithTemplateFromImage.
func (mr *MockExtensionMockRecorder) UpdateDescriptorSetWithTemplateFromImage(descriptorSet, template, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDescriptorSetWithTemplateFromImage", reflect.TypeOf((*MockExtension)(nil).UpdateDescriptorSetWithTemplateFromImage), descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromObjectHandle mocks base method.
func (m *MockExtension) UpdateDescriptorSetWithTemplateFromObjectHandle(descriptorSet core.DescriptorSet, template core.DescriptorUpdateTemplate, data loader.VulkanHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDescriptorSetWithTemplateFromObjectHandle", descriptorSet, template, data)
}

// UpdateDescriptorSetWithTemplateFromObjectHandle indicates an expected call of UpdateDescriptorSetWithTemplateFromObjectHandle.
func (mr *MockExtensionMockRecorder) UpdateDescriptorSetWithTemplateFromObjectHandle(descriptorSet, template, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDescriptorSetWithTemplateFromObjectHandle", reflect.TypeOf((*MockExtension)(nil).UpdateDescriptorSetWithTemplateFromObjectHandle), descriptorSet, template, data)
}
