// Code generated by MockGen. DO NOT EDIT.
// Source: loader.go
//
// Generated by this command:
//
//	mockgen -source loader.go -destination ../mocks/loader.go -package mock_descriptor_update_template
//

// Package mock_descriptor_update_template is a generated GoMock package.
package mock_descriptor_update_template

import (
	reflect "reflect"
	unsafe "unsafe"

	common "github.com/vkngwrapper/core/v3/common"
	loader "github.com/vkngwrapper/core/v3/loader"
	khr_descriptor_update_template_loader "github.com/vkngwrapper/extensions/v3/khr_descriptor_update_template/loader"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// VkCmdPushDescriptorSetWithTemplateKHR mocks base method.
func (m *MockLoader) VkCmdPushDescriptorSetWithTemplateKHR(commandBuffer loader.VkCommandBuffer, descriptorUpdateTemplate khr_descriptor_update_template_loader.VkDescriptorUpdateTemplateKHR, layout loader.VkPipelineLayout, set loader.Uint32, pData unsafe.Pointer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkCmdPushDescriptorSetWithTemplateKHR", commandBuffer, descriptorUpdateTemplate, layout, set, pData)
}

// VkCmdPushDescriptorSetWithTemplateKHR indicates an expected call of VkCmdPushDescriptorSetWithTemplateKHR.
func (mr *MockLoaderMockRecorder) VkCmdPushDescriptorSetWithTemplateKHR(commandBuffer, descriptorUpdateTemplate, layout, set, pData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCmdPushDescriptorSetWithTemplateKHR", reflect.TypeOf((*MockLoader)(nil).VkCmdPushDescriptorSetWithTemplateKHR), commandBuffer, descriptorUpdateTemplate, layout, set, pData)
}

// VkCreateDescriptorUpdateTemplateKHR mocks base method.
func (m *MockLoader) VkCreateDescriptorUpdateTemplateKHR(device loader.VkDevice, pCreateInfo *khr_descriptor_update_template_loader.VkDescriptorUpdateTemplateCreateInfoKHR, pAllocator *loader.VkAllocationCallbacks, pDescriptorUpdateTemplate *khr_descriptor_update_template_loader.VkDescriptorUpdateTemplateKHR) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCreateDescriptorUpdateTemplateKHR", device, pCreateInfo, pAllocator, pDescriptorUpdateTemplate)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCreateDescriptorUpdateTemplateKHR indicates an expected call of VkCreateDescriptorUpdateTemplateKHR.
func (mr *MockLoaderMockRecorder) VkCreateDescriptorUpdateTemplateKHR(device, pCreateInfo, pAllocator, pDescriptorUpdateTemplate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCreateDescriptorUpdateTemplateKHR", reflect.TypeOf((*MockLoader)(nil).VkCreateDescriptorUpdateTemplateKHR), device, pCreateInfo, pAllocator, pDescriptorUpdateTemplate)
}

// VkDestroyDescriptorUpdateTemplateKHR mocks base method.
func (m *MockLoader) VkDestroyDescriptorUpdateTemplateKHR(device loader.VkDevice, descriptorUpdateTemplate khr_descriptor_update_template_loader.VkDescriptorUpdateTemplateKHR, pAllocator *loader.VkAllocationCallbacks) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkDestroyDescriptorUpdateTemplateKHR", device, descriptorUpdateTemplate, pAllocator)
}

// VkDestroyDescriptorUpdateTemplateKHR indicates an expected call of VkDestroyDescriptorUpdateTemplateKHR.
func (mr *MockLoaderMockRecorder) VkDestroyDescriptorUpdateTemplateKHR(device, descriptorUpdateTemplate, pAllocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkDestroyDescriptorUpdateTemplateKHR", reflect.TypeOf((*MockLoader)(nil).VkDestroyDescriptorUpdateTemplateKHR), device, descriptorUpdateTemplate, pAllocator)
}

// VkUpdateDescriptorSetWithTemplateKHR mocks base method.
func (m *MockLoader) VkUpdateDescriptorSetWithTemplateKHR(device loader.VkDevice, descriptorSet loader.VkDescriptorSet, descriptorUpdateTemplate khr_descriptor_update_template_loader.VkDescriptorUpdateTemplateKHR, pData unsafe.Pointer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkUpdateDescriptorSetWithTemplateKHR", device, descriptorSet, descriptorUpdateTemplate, pData)
}

// VkUpdateDescriptorSetWithTemplateKHR indicates an expected call of VkUpdateDescriptorSetWithTemplateKHR.
func (mr *MockLoaderMockRecorder) VkUpdateDescriptorSetWithTemplateKHR(device, descriptorSet, descriptorUpdateTemplate, pData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkUpdateDescriptorSetWithTemplateKHR", reflect.TypeOf((*MockLoader)(nil).VkUpdateDescriptorSetWithTemplateKHR), device, descriptorSet, descriptorUpdateTemplate, pData)
}
