// Code generated by MockGen. DO NOT EDIT.
// Source: shim.go
//
// Generated by this command:
//
//	mockgen -source shim.go -destination ../mocks/shim.go -package mock_descriptor_update_template
//

// Package mock_descriptor_update_template is a generated GoMock package.
package mock_descriptor_update_template

import (
	reflect "reflect"

	common "github.com/vkngwrapper/core/v2/common"
	core1_1 "github.com/vkngwrapper/core/v2/core1_1"
	driver "github.com/vkngwrapper/core/v2/driver"
	gomock "go.uber.org/mock/gomock"
)

// MockShim is a mock of Shim interface.
type MockShim struct {
	ctrl     *gomock.Controller
	recorder *MockShimMockRecorder
	isgomock struct{}
}

// MockShimMockRecorder is the mock recorder for MockShim.
type MockShimMockRecorder struct {
	mock *MockShim
}

// NewMockShim creates a new mock instance.
func NewMockShim(ctrl *gomock.Controller) *MockShim {
	mock := &MockShim{ctrl: ctrl}
	mock.recorder = &MockShimMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShim) EXPECT() *MockShimMockRecorder {
	return m.recorder
}

// CreateDescriptorUpdateTemplate mocks base method.
func (m *MockShim) CreateDescriptorUpdateTemplate(o core1_1.DescriptorUpdateTemplateCreateInfo, allocator *driver.AllocationCallbacks) (core1_1.DescriptorUpdateTemplate, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDescriptorUpdateTemplate", o, allocator)
	ret0, _ := ret[0].(core1_1.DescriptorUpdateTemplate)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateDescriptorUpdateTemplate indicates an expected call of CreateDescriptorUpdateTemplate.
func (mr *MockShimMockRecorder) CreateDescriptorUpdateTemplate(o, allocator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDescriptorUpdateTemplate", reflect.TypeOf((*MockShim)(nil).CreateDescriptorUpdateTemplate), o, allocator)
}
