// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_external_memory_capabilities
//

// Package mock_external_memory_capabilities is a generated GoMock package.
package mock_external_memory_capabilities

import (
	reflect "reflect"

	core "github.com/vkngwrapper/core/v3"
	khr_external_memory_capabilities "github.com/vkngwrapper/extensions/v3/khr_external_memory_capabilities"
	gomock "go.uber.org/mock/gomock"
)

// MockExtension is a mock of Extension interface.
type MockExtension struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionMockRecorder
	isgomock struct{}
}

// MockExtensionMockRecorder is the mock recorder for MockExtension.
type MockExtensionMockRecorder struct {
	mock *MockExtension
}

// NewMockExtension creates a new mock instance.
func NewMockExtension(ctrl *gomock.Controller) *MockExtension {
	mock := &MockExtension{ctrl: ctrl}
	mock.recorder = &MockExtensionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtension) EXPECT() *MockExtensionMockRecorder {
	return m.recorder
}

// PhysicalDeviceExternalBufferProperties mocks base method.
func (m *MockExtension) PhysicalDeviceExternalBufferProperties(physicalDevice core.PhysicalDevice, o khr_external_memory_capabilities.PhysicalDeviceExternalBufferInfo, outData *khr_external_memory_capabilities.ExternalBufferProperties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalDeviceExternalBufferProperties", physicalDevice, o, outData)
	ret0, _ := ret[0].(error)
	return ret0
}

// PhysicalDeviceExternalBufferProperties indicates an expected call of PhysicalDeviceExternalBufferProperties.
func (mr *MockExtensionMockRecorder) PhysicalDeviceExternalBufferProperties(physicalDevice, o, outData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalDeviceExternalBufferProperties", reflect.TypeOf((*MockExtension)(nil).PhysicalDeviceExternalBufferProperties), physicalDevice, o, outData)
}
