// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go
//
// Generated by this command:
//
//	mockgen -source extiface.go -destination ./mocks/extension.go -package mock_external_memory_capabilities
//

// Package mock_external_memory_capabilities is a generated GoMock package.
package mock_external_memory_capabilities

import (
	reflect "reflect"

	core "github.com/vkngwrapper/core/v3"
	khr_external_memory_capabilities "github.com/vkngwrapper/extensions/v3/khr_external_memory_capabilities"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDriver is a mock of ExtensionDriver interface.
type MockExtensionDriver struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDriverMockRecorder
	isgomock struct{}
}

// MockExtensionDriverMockRecorder is the mock recorder for MockExtensionDriver.
type MockExtensionDriverMockRecorder struct {
	mock *MockExtensionDriver
}

// NewMockExtensionDriver creates a new mock instance.
func NewMockExtensionDriver(ctrl *gomock.Controller) *MockExtensionDriver {
	mock := &MockExtensionDriver{ctrl: ctrl}
	mock.recorder = &MockExtensionDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDriver) EXPECT() *MockExtensionDriverMockRecorder {
	return m.recorder
}

// GetPhysicalDeviceExternalBufferProperties mocks base method.
func (m *MockExtensionDriver) GetPhysicalDeviceExternalBufferProperties(physicalDevice core.PhysicalDevice, o khr_external_memory_capabilities.PhysicalDeviceExternalBufferInfo, outData *khr_external_memory_capabilities.ExternalBufferProperties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhysicalDeviceExternalBufferProperties", physicalDevice, o, outData)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPhysicalDeviceExternalBufferProperties indicates an expected call of GetPhysicalDeviceExternalBufferProperties.
func (mr *MockExtensionDriverMockRecorder) GetPhysicalDeviceExternalBufferProperties(physicalDevice, o, outData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhysicalDeviceExternalBufferProperties", reflect.TypeOf((*MockExtensionDriver)(nil).GetPhysicalDeviceExternalBufferProperties), physicalDevice, o, outData)
}
