// Code generated by MockGen. DO NOT EDIT.
// Source: shim.go

// Package mock_external_memory_capabilities is a generated GoMock package.
package mock_external_memory_capabilities

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core1_1 "github.com/vkngwrapper/core/v2/core1_1"
)

// MockShim is a mock of Shim interface.
type MockShim struct {
	ctrl     *gomock.Controller
	recorder *MockShimMockRecorder
}

// MockShimMockRecorder is the mock recorder for MockShim.
type MockShimMockRecorder struct {
	mock *MockShim
}

// NewMockShim creates a new mock instance.
func NewMockShim(ctrl *gomock.Controller) *MockShim {
	mock := &MockShim{ctrl: ctrl}
	mock.recorder = &MockShimMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShim) EXPECT() *MockShimMockRecorder {
	return m.recorder
}

// ExternalBufferProperties mocks base method.
func (m *MockShim) ExternalBufferProperties(o core1_1.PhysicalDeviceExternalBufferInfo, outData *core1_1.ExternalBufferProperties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalBufferProperties", o, outData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExternalBufferProperties indicates an expected call of ExternalBufferProperties.
func (mr *MockShimMockRecorder) ExternalBufferProperties(o, outData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalBufferProperties", reflect.TypeOf((*MockShim)(nil).ExternalBufferProperties), o, outData)
}
